### ISSUE TITLE
Understand how "official" CRDs will be handled in Kubernetes project

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/service-apis#10]
The new APIs we are working on are targeted to remain as CRDs that are going to live outside the main kubernetes/kubernetes repo. While this is OK for the initial working state, at some point these will need to be made official. This issue tracks understanding what this means, how releases will be made, etc.

We need to figure out (most likely with SIG-ARCH) what this looks like.

* How do releases line up with Kubernetes versions? How are API versions referenced?
* What does qualification w/ Kubernetes look like?
* If part of the default set that users can expect, what is the install flow etc.

**Comment by robscott** [comment]
Had a great call with @liggitt and @bowei today to talk through what this would look like. Some highlights:

- VolumeSnapshot is the first example of an "official CRD" in use. These definitions are automatically installed by CSI drivers that support them (https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/)
- CRDs do not need to be tied to Kubernetes versions, the release cycle is independent. The primary requirement of an official CRD is that it goes through the KEP process.
- Versioning should be well thought out, with several alphas, and a great deal of API stability before releasing a beta. 
- Conversions between different versions would not be straightforward, so in general, alpha would be used to verify that controllers can work with this API and that it makes sense, and a beta release would be the first version consumed by most end users.
- When upgrading to beta, we can remove alpha versions from the list of supported versions and require anyone with alpha resources (should be very few) to replace them with beta resources.
- Although VolumeSnapshot CRDs could be installed directly by CSI drivers that support them, we need to support multiple controllers per cluster, so the CRDs should live in and be installed from this repo. There are a variety of ways to simplify that process and integrate it with controller installation, we'll need to discuss specifics around this more. 

/close

**Comment by bowei** [comment]
Actually -- rob, can we document the output of the discussions before closing this issue?

**Comment by bowei** [comment]
You can put it under a new page in the docs-srcs "Releases"

**Comment by howardjohn** [comment]
> Conversions between different versions would not be straightforward, so in general, alpha would be used to verify that controllers can work with this API and that it makes sense, and a beta release would be the first version consumed by most end users.

Maybe this is what you meant by the above, but how will we handle conversion webhooks? It seems like we cannot really support that since the CRD is shared between multiple controllers, yet only one service can be the service for conversion

**Comment by robscott** [comment]
@howardjohn I had thought that both CRDs and any conversion webhooks would be installed from this repo, essentially the shared prerequisites for any controller implementation would live here. I should clarify that in #32.

**Comment by howardjohn** [comment]
> I had thought that both CRDs and any conversion webhooks would be installed from this repo, essentially the shared prerequisites for any controller implementation would live here. I should clarify that in #32.

That SGTM.
