### ISSUE TITLE
Rename TrafficSplit API Type

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#108]
**What would you like to be added**:
IMO the `TrafficSplit` API name does not properly reflect the intention of the API. The API should do more that "split" traffic. After traffic is split among multiple backends, the API should be able to manipulate the request, i.e. add/remove headers.

**Why is this needed**:
To support Istio, Knative and other use cases that perform request manipulation after a routing decision is made.

/assign @bowei 

xref: https://github.com/kubernetes-sigs/service-apis/pull/57

**Comment by robscott** [comment]
@danehans I think this can be closed given the consensus around your approach here: https://github.com/kubernetes-sigs/service-apis/pull/57.

**Comment by danehans** [comment]
Closing due to https://github.com/kubernetes-sigs/service-apis/pull/57
