### ISSUE TITLE
Infer group `networking.x.k8s.io` from native resource types

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#109]
**What would you like to be added**:
The ability to infer group `networking.x.k8s.io` for native resource types. Group `core` is inferred for the `Service` resource. Extended this idea to infer `networking.x.k8s.io` for native resources such as `HTTPRoute`.

**Why is this needed**:
Simplify the UX.

/assign @bowei 
/cc @Miciah

**Comment by robscott** [comment]
@danehans I think this came from a time when we still had RouteObjectReference. I've looked through our other ObjectRefs and haven't found any remaining ones that would reference `networking.x-k8s.io` types, do you think this is safe to close now?

**Comment by danehans** [comment]
This issue is no longer valid now that gateway<>route binding is being accomplished with selectors.
