### ISSUE TITLE
Generated protobufs for the API

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/service-apis#11]
Most (all?) Kubernetes APIs have autogenerated protobuf messages from the go schema. It would be useful to have these generated for the types here as well

**Comment by aledbf** [comment]
@howardjohn protobuf is not supported in CRDs https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility

**Comment by howardjohn** [comment]
Interesting, I didn't realize that. For my particular use case we have a system that is basically a protobuf processor. We cannot do anything unless the types are proto message, so we would probably need to generate the protos for our case, even if Kubernetes isn't using them internally. So either way we will probably need to end up generating the protos. It seems reasonable to do this in this repo but we could do it in our own repo if needed

**Comment by howardjohn** [comment]
I was able to sort of run this locally, but I had to do a lot manually hacks.

Command: `go-to-protobuf --proto-import=$GOPATH/src/k8s.io/kubernetes/vendor --proto-import=$GOPATH/src/k8s.io/kubernetes/third_party/protobuf --packages sigs.k8s.io/service-apis/api/v1alpha1 -o /tmp/proto`

First issue is the line `SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}` seems to blow up. Not 100% sure why or how to get around this, I just deleted the line as a workaround.
Next issue is the `sigs.k8s.io` messes with protobuf name resolution. I had to add a leading `.` to all the ListMeta and ObjectMeta references

At this point we have a generated proto and pb.go file. The problem is when you try to import this go file, you will get errors since all the structs are duplicated. Moving this out to a different package still doesn't solve the problem, since some aliases like ListenerErrorReason are then undefined.

**Comment by bowei** [comment]
Is there a cross post w/ the API machinery folks? This may be something that broader than our current use case.

**Comment by howardjohn** [comment]
current script I am using to do this. Its a major hack though, just for future reference:

```sh
#!/bin/bash

set -ux

tmp=$(mktemp -d)

# HACK: remove SchemeBuilder since it doesn't behave well with go-to-protobuf
mkdir -p tmp/api/v1alpha1
find api/v1alpha1 -type f -exec sh -c 'grep -vE SchemeBuilder {} > tmp/{}' \;
rm -r api
mv tmp/api .

# Generate the protos
go-to-protobuf --proto-import=$GOPATH/src/k8s.io/kubernetes/vendor --proto-import=$GOPATH/src/k8s.io/kubernetes/third_party/protobuf --packages sigs.k8s.io/service-apis/api/v1alpha1 -o ${tmp}

# HACK: generated proto is resolved wrong due to issues with sigs.k8s.io and k8s.io. Add a leading dot, and rerun protoc
sed -i 's/optional k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta/optional .k8s.io.apimachinery.pkg.apis.meta.v1.ListMeta/g' ${tmp}/sigs.k8s.io/service-apis/api/v1alpha1/generated.proto
sed -i 's/optional k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta/optional .k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta/g' ${tmp}/sigs.k8s.io/service-apis/api/v1alpha1/generated.proto
protoc -I . -I ${tmp} -I $GOPATH/src/k8s.io/kubernetes/vendor -I $GOPATH/src/k8s.io/kubernetes/third_party/protobuf --gogo_out=${tmp} ${tmp}/sigs.k8s.io/service-apis/api/v1alpha1/generated.proto

# Copy output to final location
mkdir -p protos/v1alpha1
cp ${tmp}/sigs.k8s.io/service-apis/api/v1alpha1/generated.pb.go protos/v1alpha1

# HACK: for some reason we lose type alias
echo "type ListenerErrorReason string" >> protos/v1alpha1/generated.pb.go

# Clean up hacks
git checkout -- api
```

**Comment by aledbf** [comment]
@howardjohn I am not sure this should be added (in this repository) until protobuf are supported (personal opinion). Why? Users will find the definitions and expect to work ootb using the controller.

**Comment by howardjohn** [comment]
If there is no desire to check this into this repo, thats fine with me, although I would prefer them here. However, I hope we can at least make the changes required to remove the above hacks so its feasible to generate the protobufs, assuming the changes are not invasive.

**Comment by howardjohn** [comment]
I have this working now with only one minor hack now. Will send a PR out later after a few dependant ones merge
