### ISSUE TITLE
Specify what an empty GatewayClass field means.

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#116]
If a `Gateway` has an empty `GatewayClass` field, the result is unspecified. Implementors could use some sort of cluster default, or could reject it the gateway outright. This behavior should be specified.

**Comment by hbagdi** [comment]
Ingress V1 is shipping with the notion of a `default` ingress class, via an annotation on the IngressClass resource. We could adopt the same concept.

**Comment by jpeach** [comment]
Ingress V1 spec is [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#default-ingressclass). There's an assumption that an admission controller prevents multiple classes being the default, but IIUC, that is intrinsically race and an admission controller can't guarantee to enforce that.

**Comment by hbagdi** [comment]
gatewayClassName is a required field and so we should not have this problem now.
@jpeach, is that sufficient?

**Comment by jpeach** [comment]
yup

/close
