### ISSUE TITLE
User Story: workload portability

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#122]
**What would you like to be added**:

Workloads should be portable between gateway classes. This means that the behavior of objects in the API should be specified in enough detail that different implementations can be compatible.

**Why is this needed**:

As an operator, I want to be able to change the GatewayClass without disturbing user workloads. I may need to choose a different GatewayClass for operational reasons (e.g. proxy reliability) or business reasons (e.g. license or usage charges).

As a developer, I want to be be able to deploy my workload to different GatewayClasses without rewriting it. I may need to do this to take advantage of different quality of service or cost parameters.

**Comment by bowei** [comment]
This story needs more details as to what "disturbing" means.

Does this mean no requests get dropped? (probably not a possible, even between classes implemented by the same controller)
Does this mean between classes there is a known behavior (basically what we are trying to define overall).

**Comment by jpeach** [comment]
> This story needs more details as to what "disturbing" means.

Good point. I meant that the developer should not have to alter the configuration (i.e. YAML) other than to flip the gateway class reference. 

> Does this mean no requests get dropped

Nope.

> Does this mean between classes there is a known behavior (basically what we are trying to define overall)

Yes, exactly. I wanted to capture that goal as an explicit user story.

**Comment by jpeach** [comment]
/reopen /remove-lifecycle rotten

We can probably address this user story by some contextual paragraph in the documentation.
