### ISSUE TITLE
TLS: Support Pass Through Connections

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#123]
**What would you like to be added**:
The ability for service-apis to support "passing through" a client-side TLS connection to an in-cluster object.

**Why is this needed**:
I have an app security requirement that states client tls connections must be end-to-end. Therefore the TLS connection can not be terminated on a Gateway.

xref: https://github.com/kubernetes-sigs/service-apis/issues/52

/assign @bowei 
/cc @jpeach @youngnick @Miciah

**Comment by bowei** [comment]
https://github.com/kubernetes-sigs/service-apis/issues/94

**Comment by hbagdi** [comment]
On a closer inspection, #94 and #123 are not duplicate of each other. #94 is about TLS termination by the proxy while this one is about routing based on SNI with no TLS termination. I've summarized both of these in #96. PTAL.

**Comment by hbagdi** [comment]
@danehans With #256 merged in, is it safe to close this?

**Comment by hbagdi** [comment]
Considering this resolved.
Please re-open if otherwise.
/close.
