### ISSUE TITLE
TLS: Add Support for Gateway Reencryption

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#124]
**What would you like to be added**:
The ability for service-apis to support terminating a client-side TLS connection at the gateway and have the gateway create a new TLS connection to an in-cluster object.

**Why is this needed**:
I have an app security requirement that requires the gateway to perform specific checks, modifications, etc.. of http headers before forwarding the request to my in-cluster TLS service.

xref: https://github.com/kubernetes-sigs/service-apis/issues/52

/assign @bowei 
/cc @jpeach @youngnick @Miciah

**Comment by robscott** [comment]
I believe this will be addressed by https://github.com/kubernetes-sigs/service-apis/pull/256 and https://github.com/kubernetes-sigs/service-apis/pull/268.

/remove-lifecycle stale

**Comment by hbagdi** [comment]
@danehans Given the state of the API now, do you think it is safe to close this?

**Comment by hbagdi** [comment]
Considering this resolved.
Please re-open if otherwise.
/close.
