### ISSUE TITLE
Support regex matching for HTTP header

### ISSUE THREAD

**Issue by igsong** [kubernetes-sigs/service-apis#129]
Currently, only the exact matching is supported for HTTP header.
https://github.com/kubernetes-sigs/service-apis/blob/31cbedd591ab43d2750ee1dd1f151b13f95dc1bd/api/v1alpha1/httproute_types.go#L91-L93

Therefore, I would like to propose support of regex matching on HTTP header.
If the regex matching is supported here, it would be very helpful to greatly increase flexibility.

**Comment by danehans** [comment]
xref [this](https://docs.google.com/document/d/12t_3NE4EqvW_l0hfVlQcAGKkwkAM56tTn2wN_JtHbSQ/edit?usp=sharing) doc for add'l use case details.

**Comment by hbagdi** [comment]
@danehans The doc is restricted. Can you open it up to the world?

**Comment by hbagdi** [comment]
>  If the regex matching is supported here, it would be very helpful to greatly increase flexibility.

Are you looking for regex matching on the header value or header key or both?

**Comment by igsong** [comment]
Oh. the regex matching for the header value works for me :)

**Comment by ZhiminXiang** [comment]
@hbagdi you need to join group https://groups.google.com/g/knative-users to get the permission for access the doc.

**Comment by hbagdi** [comment]
HeaderMatchType of "ImplementationSpecific" can now achieve this.

Given the variety of regex engines that exist in implementations, it is unlikely that this will make into the core API.
Please re-open if needed.
/close

**Comment by howellshan** [comment]
> x matching for the header value

is there an example that can show how regex matching works for the header value? Does the expression below work for all the headers with name "Sec-WebSocket-Protocol" and value start with "test"?
          headers:
            - type: RegularExpression
              name: Sec-WebSocket-Protocol
              value: "test*"

and how about multiple values, does it work something like below?
          headers:
            - type: RegularExpression
              name: Sec-WebSocket-Protocol
              value: "test*,prod*"
