### ISSUE TITLE
Define a reference implementation of TCPRoute

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/service-apis#131]
**What would you like to be added**:
A reference implementation of the `TcpRoute` class.

**Why is this needed**:
Currently the `TcpRoute` class is TBD, and it would be nice to have a reference implementation of this type for people wanting to work with or build on the Service API v2.

**Comment by hbagdi** [comment]
xref #96

**Comment by jpeach** [comment]
Do you mean a reference implementation (as in a controller that implements the spec in a conformant way), or did you mean that the `TCPRoute` type should be designed and specified?

**Comment by hbagdi** [comment]
I thought TCPRout was more fleshed out but all we have in `TCPRouteMatch` is an extensionRef.

> did you mean that the TCPRoute type should be designed and specified?

@akutz I'm assuming you meant this one. Do you have any ideas on what you wish to see here?

**Comment by akutz** [comment]
I think this can be closed based on #236.
