### ISSUE TITLE
Support ClusterGatewayClass and GatewayClass

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/service-apis#136]
## What would you like to be added
A new, cluster-scoped `ClusterGatewayClass` and changing `GatewayClass` to a namespaced resource. This is a P0 ask for our project. The details are in the next section. Thank you!

## Why is this needed
There is a comment at https://github.com/kubernetes-sigs/service-apis/pull/130#issuecomment-611828125 that states:

> Yep, gateway is closest in concept to a virtual host that can be configured on some arbitrary load balancing data plane. We should keep iterating to clarify the docs :)

If this is the case, then the current model does not work for situations when:

* the construct that provisions virtual hosts is a cluster-scoped resource and 
* the virtual hosts need to be namespaced.

We have a requirement for a load balancer per namespace where the load balancer provisions virtual servers. 

### Current Model
Currently the Service APIs approach is for a `GatewayClass` to be cluster-scoped and provision namespaced `Gateway` resources. For example, there is:

* a *:1 relationship between cluster-scoped `GatewayClass` resources and a load balancer service control plane
* a 1:1 relationship between namespaced `Gateway` resources and a load balancer
* a *:1 relationship between the listeners on namespaced `Gateway` resources and the load balancer's virtual hosts

![image](https://gist.githubusercontent.com/akutz/0065b5e10a8955349945ecff17e265a3/raw/7d03b19249cc0a49726f301341e738e7f4902668/gateway_and_gateway_class_with_single_lb_control_plane.svg?sanitize=true)

### Proposed Model
However, if the `Gateway` is the virtual host on a load balancer, then the `GatewayClass` is the load balancer, and we need to support the following model:

* a *:1 relationship between namespaced `GatewayClass` resources and a load balancer service control plane
* a 1:1 relationship between namespaced `GatewayClass` resources and a load balancer
* a 1:1 relationship between namespaced `Gateway` resources and a virtual host on the load balancer

![image](https://gist.githubusercontent.com/akutz/0065b5e10a8955349945ecff17e265a3/raw/7d03b19249cc0a49726f301341e738e7f4902668/namespaced_gateway_class.svg?sanitize=true)

#### Cluster scoped resources

We do not currently have a need for a cluster-scoped resources, but since `GatewayClass` is currently cluster-scoped, a new type, `ClusterGatewayClass`, could continue to fulfill this role.

### Conclusion

This is a P0 ask for our project. Without this we will have to continue to treat the `Listener` as the virtual host, and that is in stark contrast to the conversation we had on the last office hours based on #130 and [_Service APIs v2: L4 Boogaloo_](https://docs.google.com/document/d/1AUs27024agOWkg_Cqk10toNo_OXOvTb2HM0mWaLFF1w/edit?usp=sharing) :)

xref #83

cc @maplain @andrewsykim

**Comment by akutz** [comment]
cc @detiber I thought you might like to be looped in on some of the conversations regarding the LB work we're doing we want to base on the Service APIs v2. Since you are working on Cluster API provider for AWS, maybe you will eventually have a similar vested interest.

**Comment by robscott** [comment]
Thanks for writing this up, a lot of good thoughts here. I don't have answers for everything, but here are a few thoughts:

* We did consider separate `Cluster` scoped resources as we were developing the [security model](https://github.com/kubernetes-sigs/service-apis/blob/master/docs-src/security-model.md#new-api-resources). Ultimately we determined that adding additional resources was not the best way to solve this problem. As an example, having resources be tied to either a namespace or cluster scope is not particularly helpful if you want a resource to be available in a subset of resources.

* GatewayClass is currently scoped to define a class/type of Gateway. This includes the controller that should implement it, where it can be used, and what it can target. It also provides a way to link to additional controller specific parameters that may be relevant to the implementation. As an example, this would be how you would differentiate between an external and internal load balancer. I don't think it makes sense for GatewayClass to represent an actual load balancer, but I can see the potential value in rethinking how we're mapping load balancers and virtual hosts to resources in this API. 

* Whether or not GatewayClass is cluster scoped, we want to enable the same GatewayClass being used by Gateways in multiple namespaces. Currently we accomplish this with a namespace selector that indicates which namespaces can use this GatewayClass for a Gateway. We also separately allow GatewayClass administrators to limit where Routes can be referenced for a Gateway using a given class.

* The concept of GatewayClass closely mirrors the similarly cluster scoped IngressClass and StorageClass resources in Kubernetes. In all cases, referencing one of these classes is as simple as adding a *ClassName type attribute to the associated resource. Although we could make GatewayClass namespace-scoped, it would:
    * contradict an already established pattern
    * make references more complex 
    * potentially result in duplicate GatewayClass names in a cluster

I think the current model supports a Gateway per namespace well, it's definitely something we've discussed. What I think the root issue here is that a Gateway in its current form does not do well at defining both a load balancer _and_ its virtual hosts. I'm interested in if there's a path forward to defining both with modifications to that type and/or changes to Routes, or if we need an additional resource.

Interested in perspectives from others on this as well.
/cc @danehans @hbagdi @jpeach @youngnick

**Comment by akutz** [comment]
Hi @robscott,

Thanks for the feedback!

As you said, the ultimate issue is this -- you cannot declare the `Gateway` is the _virtual host_ and not have something representing the load balancer for load balancer solutions that have distinct LB *and* virtual server constructs. 

This is one approach to solve that -- mapping the `GatewayClass` to the LB construct in the model with virtual servers.

> I think the current model supports a Gateway per namespace well, it's definitely something we've discussed.

It supports a `Gateway` per namespace, but as James pointed out, this is a virtual host. There are *many* common load balancer solutions -- NSX, AVI, HAProxy, even MetalLB -- that have a *:many model for LB:VirtualHost. This **is** a common architecture.

I need to understand if this project is interested in supporting these LB solutions. If so, then on multi-tenant clusters, load balancers may need to be namespaced. As it is, Service APIs v2 is incompatible with LB providers that have virtual servers if `GatewayClass` does not map to the LB. 

I have a real-world need for this, and this is my second attempt at reconciling this issue. What do you need from me to help make that happen? Because as I see it, we either we need to:

* Define a `VirtualHost` CRD that maps to `Gateway` resources if people want to support that or
* Acknowledge that `Gateway` is a virtual host and `GatewayClass` is a load balancer and the latter must also support being namespaced

Thanks!

**Comment by robscott** [comment]
I've talked with @akutz some more on Slack to better understand the use case, and I think it's both worth handling and relatively straightforward to achieve. If I'm understanding the use case correctly, in some multi-tenant on-prem deployments it's desirable to have separate physical load balancers for each Kubernetes namespace. This relationship could be modeled with unique GatewayClasses per namespace. Of course the current cluster-scoped concept of GatewayClass is not ideal for this use case. It seems like transitioning GatewayClass to a namespace-scoped resource could help for this use case and potentially others. 

We've at least discussed the potential of namespace-scoped GatewayClasses in the past, and I've outlined some of the disadvantages of that approach in my earlier comment. With that said, there are also some advantages:

* Less potential for naming conflicts. With each GatewayClass defined in a namespace, a common pattern might be for a controller and the GatewayClasses it implements to be deployed in the same namespace. 
* Potential for simple and secure defaults that could only allow Gateways and Routes in the same namespace by default, with optional extensions to that using the existing selectors.
* GatewayClass parameters do not need to be cluster-scoped. This is potentially a big win for organizations that want to allow users to configure parameters for some GatewayClasses but not all.
* More flexibility with RBAC roles and bindings.

Of course there are still some significant disadvantages to this approach:

* Inconsistent with the cluster-scoped IngressClass and StorageClass resources.
* Requires an additional (optional) class namespace parameter on Gateways.

I'm interested in this approach as I think it could potential solve a couple potential use cases and provide some more secure defaults, any thoughts? If there's sufficient interest in this change, I'm happy to create a PR that would implement this.

**Comment by jpeach** [comment]
> If I'm understanding the use case correctly, in some multi-tenant on-prem deployments it's desirable to have separate physical load balancers for each Kubernetes namespace.

With the current API semantics, here's how I would try to approach this.

You create a controller that is able to allocate proxies (i.e. physical or virtual load balancers that can be configured to host gateways). When the user creates a Gateway in a namespace, then the controller implicitly allocates a proxy for that namespace. Depending on the properties of the namespace or the request, maybe multiple proxies could be allocated to a namespace. The controller could also be configured to only do this for namespaces that are privileged in some way.

My perspective is that services API doesn't prescribe how the infrastructure works, or exactly what the implementation of a gateway class is. This means that it can work however you want. If you can build infrastructure where every gateway is backed by physical servers, then that's great and it will totally work. There's nothing in the API that models the underlying infrastructure; that's entirely abstracted behind the gateway class. My impression has always been that this is underspecified on purpose to allow there to be a wide variety of infrastructure implementations.

**Comment by hbagdi** [comment]
I had the same understanding as James here.

I do recall that in early discussions of the project, we had discussions around how some controllers treat each Ingress v1 resource as independent Ingress/LB point while others flatten out multiple Ingress resources and satisfy them via a single LB instance. Then, we had agreed that multiple Gateways could be "satisfied" by a single proxy/LB and that is an implementation detail of a GatewayClass. 

This almost feels like we can leverage Gateway as a VirtualHost (as defined in our meeting discussions) or as a representation of a real/virtual LB.

**Comment by jpeach** [comment]
> I had the same understanding as James here.
> 
> I do recall that in early discussions of the project, we had discussions around how some controllers treat each Ingress v1 resource as independent Ingress/LB point while others flatten out multiple Ingress resources and satisfy them via a single LB instance. Then, we had agreed that multiple Gateways could be "satisfied" by a single proxy/LB and that is an implementation detail of a GatewayClass.
> 
> This almost feels like we can leverage Gateway as a VirtualHost (as defined in our meeting discussions) or as a representation of a real/virtual LB.

I'm increasingly thinking of GatewayClass a *pointer to infrastructure*. That's not the best way to document it, but I think that it is useful to frame it as a handle to some infrastructure capability rather than being infrastructure itself.

**Comment by maplain** [comment]
> My perspective is that services API doesn't prescribe how the infrastructure works, or exactly what the implementation of a gateway class is. This means that it can work however you want.

It actually forces the infrastructure to be cluster-scoped. For instance in your example, the GatewayClass watches Gateways in namespaces then allocates Proxies into the namespace.

If tenants are namespace scoped, and they want to deploy GatewayClass controller into their own namespace, this wouldn't work cuz the Controller simply cannot access the Cluster scoped resource.

**Comment by bowei** [comment]
@maplain -- this issue is now closed, it would be good to file a new issue to continue the discussion.

**Comment by robscott** [comment]
I think https://github.com/kubernetes/kubernetes/issues/99824 is a good follow up to this.
