### ISSUE TITLE
How are the initial GatewayClass conditions set?

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#142]
The concepts doc says:

> A new GatewayClass will start with the InvalidParameters condition set to Unknown. At this point the controller has not seen the configuration. Once the controller has processed the configuration, the condition will be set to False:

This sounds great, but what are the mechanics that implement this?  There's nothing that does this today, so is the plan that there would be a service-apis admission controller to initialize the conditions?

**Comment by robscott** [comment]
This is a great question. It seems like this will have to be tied to how we implement defaults as a whole, and fortunately that seems like [something we can do with OpenAPI schemas](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190426-crd-defaulting.md) in Kubernetes 1.16+ (earlier with a feature gate enabled). Here's an example of how we can do that with Kubebuilder: https://github.com/kubernetes-sigs/controller-tools/pull/323. I'll work on a PR that adds an initial example of this that covers this use case.

**Comment by jpeach** [comment]
> This is a great question. It seems like this will have to be tied to how we implement defaults as a whole, and fortunately that seems like [something we can do with OpenAPI schemas](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190426-crd-defaulting.md) in Kubernetes 1.16+ (earlier with a feature gate enabled). Here's an example of how we can do that with Kubebuilder: [kubernetes-sigs/controller-tools#323](https://github.com/kubernetes-sigs/controller-tools/pull/323). I'll work on a PR that adds an initial example of this that covers this use case.

So it looks like you can now default a field with an object? That looks really cool. Do you think it will work correctly with the status sub resource?
