### ISSUE TITLE
The API group should likely be networking.x-k8s.io

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/service-apis#147]
Currently this project's API group is `networking.x.k8s.io`, but based on conventions as I understand them, the group should be `networking.x-k8s.io`. The latter convention is used by Cluster API, Kind, and others. If nothing else, technically `networking.x.k8s.io` still falls under the now prohibited domain of `k8s.io`. If the goal is to not be `k8s.io`, we should `s/x.k8s.io/x-k8s.io/`

/kind bug

**Comment by robscott** [comment]
You're completely right, we've discussed this before but not properly documented it. As I recall, @bowei volunteered to fix this.

/assign @bowei

**Comment by bowei** [comment]
Did I never push the PR? Thought I put it up already...

**Comment by akutz** [comment]
I didn't look for a PR, just an open issue. Crap.

**Comment by akutz** [comment]
I do not see one in https://github.com/kubernetes-sigs/service-apis/pulls?q=is%3Apr+x-k8s.io+.

**Comment by bowei** [comment]
let me push it, looks like I forgot
