### ISSUE TITLE
Clarify L7 vs L4 orientation and goals

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/service-apis#157]
Please feel free to flag as dupe or close if redundant (see comment at the end of the issue)

**What would you like to be added**:

Broaden examples of gateway usecases, specifically to highlight how layers < 7 flows would work/look like, so as to clarify overall context of API Classes.

**Why is this needed**:

- The APISketch precursor doc seems to imply that we are going down the network stack: "This is a proposal for the evolution of the existing K8s Ingress API. " ... followed soon after by ". Expand its scope to include both L4 and L7 protocols".
https://docs.google.com/document/d/1BxYbDovMwnEqe8lj8JwHo8YxHAt3oC7ezhlFsG_tyag/preview# states

- However, other recent issues and some aspects of the data model imply that an L7-centric world view is more of the focus, in particular, https://kubernetes-sigs.github.io/service-apis/concepts/ seems to have exactly one canonical example, which is based on a TLS flow through a gateway.

- The APISketch has a table which differentiates `core` from `extended` support in the API, where in particular http/https are core and all other protocols (inlcuding raw TCP) are extended.  Curious if that is part of the current spec as well, or just part of the spec, and what the real-world implications might be there. 

This issue might be redundant to #135 and #136, but I just wanted to write it up to reflect my 'newcomer' viewpoint.  Am not suggesting any necessary change to the APIs at all, as I'm just learning about how this work is evolving.

**Comment by jpeach** [comment]
xref #96 #94 #66

**Comment by bowei** [comment]
TCP and UDP  (L4) are intended to be core. Most likely effort was spent on L7 (http) just because that is where a ton of the issues were seen to lie...

**Comment by bowei** [comment]
But it's good that the L4 conversation is coming back up

**Comment by jayunit100** [comment]
If there is a limit to how low Service APIs will go,  i suspect its worth clarifying the modulo be tween this, and the L3 Service work going on, and wether those streams are capable of merging ... https://docs.google.com/document/d/1Mot1dLO1kpVtIGib_wss8tWYNVMjlhVHVD0ZGJVXC6c/edit#heading=h.y8oyw4t5tboe

**Comment by robscott** [comment]
Now that we have more protocols supported I think this is more clear, feel free to reopen if not.
