### ISSUE TITLE
Define HeaderType Support for HTTPRoute

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#159]
**What would you like to be added**:
A clear definition of HeaderType support for HTTPRoute similar to PathType.

**Why is this needed**:
So users can proceed with HTTPRoute implementations.

**Comment by jpeach** [comment]
This issue refers to https://github.com/kubernetes-sigs/service-apis/blob/master/api/v1alpha1/httproute_types.go#L118

> 	// HeaderType defines the semantics of the `Header` matcher.
	//
	// +optional
	HeaderType *string `json:"headerType" protobuf:"bytes,3,opt,name=headerType"`
	// Header are the Header matches as interpreted via
	// HeaderType.
	//
	// +optional
	Header map[string]string `json:"header" protobuf:"bytes,4,rep,name=header"`

**Comment by danehans** [comment]
background: https://kubernetes.slack.com/archives/CR0H13KGA/p1587056565055500
