### ISSUE TITLE
HTTPRoute Status

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#162]
**What would you like to be added**:
Status conditions for an `HTTPRoute`. For example, how should a route condition such as an invalid target port be handled?

**Why is this needed**:
To surface conditions of an `HTTPRoute`.

/assign @bowei

**Comment by danehans** [comment]
xref: https://github.com/kubernetes-sigs/service-apis/pull/185 as a use case for `MirrorTo` status conditions.

**Comment by hbagdi** [comment]
@danehans @jpeach  Is this safe to close now?

**Comment by jpeach** [comment]
/assign
/lifecycle-remove rotten

I'll reference this when I update the route conditions.

**Comment by hbagdi** [comment]
xref #371

**Comment by jpeach** [comment]
The WD office hours call, @danehans suggested a "Degraded" condition type on the route. This could be used by controllers that are able to partially apply route config.

**Comment by hbagdi** [comment]
@jpeach Can we close this now?

**Comment by jpeach** [comment]
> @jpeach Can we close this now?

I'll defer to @danehans since he filed this issue.
