### ISSUE TITLE
Remove or Clarify the behavior of “Default” field in HTTPRouteSpec

### ISSUE THREAD

**Issue by yiyangy** [kubernetes-sigs/service-apis#175]
**The behavior of the "Default" field in HTTPRouteSpec needs to be clarified.** 

For example, in the following cases:
- One Gateway can have multiple HTTPRoutes, each with a Default.
- Is Default for no match of hostname only? Or more strongly, any no match? e.g. there is a hostname match, but neither path nor header match.
- For Default, should there only be one HTTPRouteRule with no HTTPRouteMatch, at most one HTTPRouteFilter and one HTTPRouteAction?

**Shall the “Default” field be removed?**

For any case with no match, simply serve 404. Then a match must be added.

@bowei

**Comment by bowei** [comment]
/remove-lifecycle

@yiyangy -- has this been addressed in the documentation?

**Comment by yiyangy** [comment]
"Default" field has been removed from HTTPRouteSpec by #258.

**Comment by hbagdi** [comment]
Closing because this is no longer an issue. Pleaes re-open if otherwise.
/close
