### ISSUE TITLE
AddressType of Listener in Gateway to represent IPv4, IPv6, dual stack and named address

### ISSUE THREAD

**Issue by yiyangy** [kubernetes-sigs/service-apis#176]
AddressType specifies the type of address for Listeners associated with a Gateway. Discuss what types should be defined to represent cases of IPv4, IPv6, dual stack and named address.

- IPv4Address - represents an IPv4 Address
- IPv6Address - represents an IPv6 Address

Reference: [EndpointSlice AddressType field](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/discovery/types.go#L41)

- NamedAddress

Use case: Static IP address

Example: Ingress GCE
Annotation [kubernetes.io/ingress.global-static-ip-name](https://github.com/kubernetes/ingress-gce/blob/master/pkg/annotations/ingress.go#L42)

If a permanent IP address is wanted that stays the same across deleting Ingress and creating a new one, a static IP address must be reserved. Such a static IP address is reserved for a customer’s project until they decide to release it. A name is specified to call this address. Then in the Ingress manifest, the annotation “kubernetes.io/ingress.global-static-ip-name” is included that gives the name of the reserved static IP address.

**Comment by jpeach** [comment]
Is `NamedAddress` in this sense an arbitrary string identifying an infrastructure resource, or is it a DNS FQDN?

**Comment by yiyangy** [comment]
The former - an arbitrary string identifying an infrastructure resource

**Comment by robscott** [comment]
I think this has actually been resolved now. We have both `NamedAddress` and `IPAddress` as types. I don't think we have any reason to differentiate between IPv4 and IPv6 addresses. Feel free to reopen if I missed anything though.

/close
