### ISSUE TITLE
go-to-protobuf incorrectly generates godocs

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#178]
This is a tracker issue tracking https://github.com/kubernetes/code-generator/issues/107.

**Comment by danehans** [comment]
This issue was observed during review of https://github.com/kubernetes-sigs/service-apis/pull/163.

**Comment by jpeach** [comment]
xref #210

**Comment by jpeach** [comment]
Protobuf generation was removed, so this issue is no longer needed.

/close
