### ISSUE TITLE
Support levels (core, extended, custom) are not documented

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#195]
This was discussed in one of our recent meetings. I know the original sketch doc briefly mentions core and extended types, but I'm not sure what custom would mean. It would be good to document how these should be interpreted. As an example, these [three levels are referenced here](https://github.com/kubernetes-sigs/service-apis/blob/master/api/v1alpha1/httproute_types.go#L104-L106).

/assign @bowei

**Comment by danehans** [comment]
> Delineating support levels could be tricky when multiple features interact.

This issue arose during our office hours discussion on [per target actions](https://docs.google.com/document/d/1SkTb6ECuiQiayvumdsZ3sxDcXD6cYs-DKB_C81Ajvh4/edit?usp=sharing). Actions can be categorized as core, extended or custom, but creating a route rule containing a combination of them may be implementation specific.
