### ISSUE TITLE
Protocol type extensibility

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#203]
In #193, listener protocol type is defined to be the exact set of "TCP", "TLS", "HTTP", "HTTPS". We should discuss whether implementations should be able to add their own protocol type names to this set and how what would affect listener compatibility rules and name matching.

**Comment by akutz** [comment]
+1 to removing the validation. We got bit by this on a fork, whereas otherwise we could have just used `ProtocolType("UDP")` And yes, @jpeach pointed me to https://github.com/kubernetes-sigs/service-apis/pull/239, but that isn't the root problem. Routes are currently flexible and can be anything, but this validation limits protocols to a small set of the potential values people may wish to use.

**Comment by hbagdi** [comment]
ProtocolType is now a `string` and allows for arbitrary protocols:
https://github.com/kubernetes-sigs/service-apis/blob/master/apis/v1alpha1/gateway_types.go#L146-L164

Please re-open if I'm misinterpreting the issue.
/close

**Comment by jpeach** [comment]
/reopen


ProtocolType is still an enum

https://github.com/kubernetes-sigs/service-apis/blob/master/apis/v1alpha1/gateway_types.go#L296-L305

**Comment by hbagdi** [comment]
@jpeach Is this resolved now? It is used like an enum inside the API but we intentionally:
- don't do enum validation in the CRD to allow for arbitrary protocols
- ProtocolType is an exported Go type

Please also see #390 

Is that sufficient to close this?

**Comment by jpeach** [comment]
> @jpeach Is this resolved now? It is used like an enum inside the API but we intentionally:
> 
> * don't do enum validation in the CRD to allow for arbitrary protocols

Where do you see that there's no validation?

**Comment by hbagdi** [comment]
Whoopsie. My bad.

I fixed that in #390. PTAL.

**Comment by hbagdi** [comment]
This can be closed now. Please see:
https://github.com/kubernetes-sigs/service-apis/blob/6a0eff2f33e0c84b1dfff11782689d5174194932/apis/v1alpha1/gateway_types.go#L248-L253
/close
