### ISSUE TITLE
Type aliases resolve too aggressively in the generated API documentation

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#210]
**What happened**:

All the type aliases for `ConfigMapsDefaultLocalObjectReference` end up linking back to a single documentation block. We lose the unique documentation present at each alias declaration.

Fields that are an instance of the type alias are also collapsed into the underlying type, which is not what we want.

![Screen Shot 2020-06-10 at 3 42 39 pm](https://user-images.githubusercontent.com/9917/84231234-0abb0f80-ab31-11ea-9d5e-1cb958057ea5.png)

**What you expected to happen**:

Each type alias should get its own documentation block, ie. for each of these:
```
api/v1alpha1/gateway_types.go:type ListenerExtensionObjectReference = ConfigMapsDefaultLocalObjectReference
api/v1alpha1/gatewayclass_types.go:type GatewayClassParametersObjectReference = ConfigMapsDefaultLocalObjectReference
api/v1alpha1/httproute_types.go:type RouteMatchExtensionObjectReference = ConfigMapsDefaultLocalObjectReference
api/v1alpha1/httproute_types.go:type RouteFilterExtensionObjectReference = ConfigMapsDefaultLocalObjectReference
api/v1alpha1/httproute_types.go:type RouteActionExtensionObjectReference = ConfigMapsDefaultLocalObjectReference
api/v1alpha1/httproute_types.go:type RouteHostExtensionObjectReference = ConfigMapsDefaultLocalObjectReference
```

**Comment by bowei** [comment]
This looks to be a consequence of how type aliases behave in Golang. They don't show up as actual types.
Maybe it's better to just reuse the same type instead of alias for the time being?

**Comment by jpeach** [comment]
xref https://github.com/ahmetb/gen-crd-api-reference-docs/issues/23

**Comment by jpeach** [comment]
> This looks to be a consequence of how type aliases behave in Golang. They don't show up as actual types.

The generator is using [gengo](https://github.com/kubernetes/gengo), so I think that it can distinguish type aliases in the source.

> Maybe it's better to just reuse the same type instead of alias for the time being?

One thing I was playing with is inlining the type rather than aliasing. This probably gets the same result in YAML, JAON and Go, but not in protobuf.


```
diff --git api/v1alpha1/httproute_types.go api/v1alpha1/httproute_types.go
index e290acc..ba22865 100644
--- api/v1alpha1/httproute_types.go
+++ api/v1alpha1/httproute_types.go
@@ -273,7 +273,9 @@ type TargetPort int32
 // route action within a known namespace.
 //
 // +k8s:deepcopy-gen=false
-type ForwardToTargetObjectReference = ServicesDefaultLocalObjectReference
+type ForwardToTargetObjectReference struct {
+       ServicesDefaultLocalObjectReference `json:",inline" protobuf:"bytes,1,opt,name=servicesDefaultLocalObjectReference"`
+}

 // RouteActionExtensionObjectReference identifies a route-action extension
 // object within a known namespace.
```

**Comment by jpeach** [comment]
I filed https://github.com/kubernetes/gengo/issues/180 for gengo. I agree that we should probably look for a local workaround.

**Comment by robscott** [comment]
may be fixed by changing
`type ForwardToTargetObjectReference = ServicesDefaultLocalObjectReference`
to
`type ForwardToTargetObjectReference ServicesDefaultLocalObjectReference`

**Comment by hbagdi** [comment]
https://github.com/kubernetes-sigs/service-apis/pull/378
/close
