### ISSUE TITLE
provisioning load-balancers for in-cluster proxy implementations

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#216]
This is less of a feature request and more of a question around how in-cluster proxy based controller can spawn cloud-loadbalancers with service-apis.

#### ingress v1

In Ingress v1, Ingress controller that run inside the k8s cluster (nginx, kong, contour, etc. to name a few), use a k8s Service of type `LoadBalancer` to provision a cloud load-balancer, which forwards traffic to proxies running inside the cluster, which then perform routing as required. This is possible because [cloud controller managers](https://github.com/kubernetes/cloud-provider) are implemented for every major public cloud provider.

#### service-apis

Service-apis has Gateways as a concept, which could be associated with load-balancers in the cloud. The problem here is that cloud controller managers have no understanding of this CRD, meaning, creating a Gateway Resource will not actually provision a LB. How should this then work? Should there be a k8s Service of type `LoadBalancer` that is associated with the Gateway in this case? Should cloud controllers add support for Gateway resources? 

The goal here is to start a discussion around this topic, come to agreement and explicitly document this so that the behavior can be part of the "public API" and lead to deterministic behavior across implementations.

**Comment by hbagdi** [comment]
This could also go into the larger topic of how Gateways are represented in k8s networking.
Could someone use a ClusterIP for a Gateway to treat a gateway as an intra-cluster gateway?
Someone running on-prem, who doesn't have access to cloud load-balancers, should they be allowed to use NodePort types of deployments for their Gateway?

**Comment by bowei** [comment]
Seems like there are couple of infrastructures (and these will be determined by the GatewayClass)

* Gateway APIs implemented by stuff running inside the cluster itself and exposed via the current mechanisms (ClusterIP, etc).
* Gateway APIs implemented "externally" (cloud, hardware, SDN)

For the most part, the virtual IP(s)/Port  in the status will be the relevant bit -- and it's an interesting thing to think about if DNS/service discovery integration would look like.

**Comment by hbagdi** [comment]
This API is not prescriptive of how any infrastructure related to Gateway is created, maintained or destroyed. Closing this as resolved, please re-open if needed.
