### ISSUE TITLE
Define the semantics of an undefined route selector

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#220]
the `RouteBindingSelector` says:

> // If undefined, route labels are not used for associating routes to
	// the gateway.

So if route labels are not used to associate routes in this case, what is the GatewayClass supposed to do? Is there some other way to associate routes?

**Comment by hbagdi** [comment]
This is interesting. Services can work without having a selector and there are some use-cases for that. I can't think of any use case for Gateway right now.

**Comment by robscott** [comment]
This is removed/replaced by https://github.com/kubernetes-sigs/service-apis/pull/198. The default behavior with this approach would result in matching all routes within the local namespace. Interested in any additional feedback on that approach.

**Comment by jpeach** [comment]
> This is removed/replaced by #198. The default behavior with this approach would result in matching all routes within the local namespace.

Which resource types would this match?

**Comment by robscott** [comment]
I was trying to limit the scope of that PR, but I think that question needs some follow up. I like the idea that was part of the l4 proposal by @jeremyot and @akutz to add a kind to the RouteSelector. Maybe this will end up being part of the work towards defining a TCPRoute?

**Comment by robscott** [comment]
I think this has been fixed by https://github.com/kubernetes-sigs/service-apis/pull/198 by simply removing the possibility of an undefined selector. If not, feel free to reopen.
