### ISSUE TITLE
Identify guiding principles for conflict resolution

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#224]
In office hours today we discussed the need for some guiding principles around conflict resolution. These can help us decide how to handle each potential conflict should be handled in the future.

As a starting point, one idea was to "prefer not to break things that are working." Taken further, we don't want to transition to a broken state if a user adds partially invalid configuration.

Examples of this might be:
* A Gateway is updated so that one listener becomes invalid: Any valid listeners should continue to be supported.
* A Route matching a Gateway selector is invalid: Any valid routes should continue to be supported.
* A HTTPRouteRule is invalid in an HTTPRoute: Any valid route rules should continue to be supported.

I think it would also make sense for these guidelines to apply if resources were introduced in a partially valid state, not just if they transitioned from valid to partially valid.

Does this approach sound reasonable? Are there other guiding principles that would be good to add here?

/cc @youngnick @hbagdi @jpeach @bowei

**Comment by jpeach** [comment]
> Does this approach sound reasonable?

Yes, I think so.

>  Are there other guiding principles that would be good to add here?

The main one is to define what happens with resolving selectors and resource references (as you list above).

**Comment by hbagdi** [comment]
I think we are settled on this one. Is it safe to close this?

**Comment by robscott** [comment]
Agreed, thanks for the reminder.
