### ISSUE TITLE
UDP/DTLS support

### ISSUE THREAD

**Issue by beriberikix** [kubernetes-sigs/service-apis#227]
This issue is to capture the notes from a [discussion on slack](https://kubernetes.slack.com/archives/CR0H13KGA/p1593007942248800), thanks to @jpeach!

Currently Gateways do not support [types](https://github.com/kubernetes-sigs/service-apis/blob/master/api/v1alpha1/gateway_types.go#L118) for UDP or DTLS. UDP (and DTLS) would be very welcome for supporting non-HTTP L7 protocols, which I discuss a bit in [this presentation](https://youtu.be/DqZkqSqnrFA?list=PLj6h78yzYM2MEMGCTD41MlYB8T-d9kNRT&t=323). There seems to be a bit of a discussion if HTTP/3 would be sufficient but having UDP/DTLS as types would enable implementers to create Foo Routes based on UDP.

Has there been any progress on a design to support UDP/DTLS?

Thanks!

**Comment by hbagdi** [comment]
UDP support has been merged in.
I don't we have any plans for DTLS. Maybe we can have that implemented in the custom space and if there is convergence, we can move it into extended/core space.

Should we close this?
@robscott @jpeach @bowei WDYT?

**Comment by hbagdi** [comment]
Considering this resolved.
Please re-open if otherwise.
/close.
