### ISSUE TITLE
GatewayClass Versioning

### ISSUE THREAD

**Issue by mark-church** [kubernetes-sigs/service-apis#229]
While the Gateway API itself has a version within the `networking.x-k8s.io` API group, there is no per-implementation versioning that exists. If the GW API was a single implementation inside the K8s codebase then this would be fine as the API version would refer to the spec and the implementation. In this case the `apiVersion` refers to the version of the specification but not the implementation. 

```
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
 name: my-gateway-class
spec:
 controller: example.com/my-gateway-controller
```

Controller & GatewayClass implementations will change over time and their support for or interpretation of different fields within Gateway may change over time as well as their support for extensions to the API. When these changes do happen, how is the GatewayClass to communicate that to its user such that behavior is always known and expected? The `apiVersion` isn't suitable for this because that refers to the specification for all implementations. This leads to a couple open questions to the group:

- Should an implementation/GatewayClass-specific API version be a 1st class thing (rather than some opaque data type that's left up to the implementor)?
- If yes, where and how could it exist within the spec?
- What are the conventions around GWC versioning that should exist so that it is well defined how the API versioning should be used? (Or do we not need these conventions?)

cc @bowei @robscott

**Comment by bowei** [comment]
(Discussion during the meeting)

Seems like it can be supported by encoding the version into the controller string:

e.g.

```
acme.io/controller-1.4
acme.io/controller-1.5
acme.io/controller-1.6

acme.io/controller // use default version (semantics depend on controller internal details)
```
