### ISSUE TITLE
Codegen verification doesn't work with Go modules.

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#235]
**What happened**:

```bash
$ pwd
/Users/jpeach/upstream/kubernetes/service-apis

$ ./hack/verify-codegen.sh
Running in verification mode
Generating deepcopy funcs
Generating clientset at sigs.k8s.io/service-apis/pkg/client/clientset
F0711 11:42:51.604839   90480 main.go:64] Error: Failed executing generator: some packages had errors:
errors in package "sigs.k8s.io/service-apis/pkg/client/clientset/versioned":
unable to read file "versioned/doc.go" for comparison: open /Users/jpeach/go/src/sigs.k8s.io/service-apis/pkg/client/clientset/versioned/doc.go: no such file or directory
unable to read file "versioned/clientset.go" for comparison: open /Users/jpeach/go/src/sigs.k8s.io/service-apis/pkg/client/clientset/versioned/clientset.go: no such file or directory
...
```

**What you expected to happen**:

`make verify` should pass.

**How to reproduce it (as minimally and precisely as possible)**:

Clone the repo to a path outside $GOPATH/src and run `make verify`.

The problem appears to be that I'm depending on Go modules and have not cloned the git repository into by `$GOPATH`.

**Comment by howardjohn** [comment]
Does that file exist? I wonder if maybe it fails like that if the file doesn't exist in the first place somehow?

**Comment by jpeach** [comment]
> Does that file exist? I wonder if maybe it fails like that if the file doesn't exist in the first place somehow?

Right, the file doesn't exist. It looks like the verification expects the files in $GOPATH and doesn't know about Go modules. My git repo is not in $GOPATH.

**Comment by howardjohn** [comment]
Oh got it, I read the issue wrong and thought you said inside GOPATH not outside. I'll take a look

**Comment by jpeach** [comment]
> Oh got it, I read the issue wrong and thought you said inside GOPATH not outside. I'll take a look

Thanks! I clarified the problem description :)

**Comment by jpeach** [comment]
`verify-codegen` doesn't generate client sets since #301 so this is no longer an issue.
