### ISSUE TITLE
Limit Disruptive GatewayClass Changes

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#245]
As I've been exploring [conflict resolution](https://docs.google.com/document/d/1ArLzUF_oJr3jV-fhXKfaEBsvRXW-6p6UuaB9FGuosIg/edit) one of the guiding principles that has emerged is to "not break things that are currently working." As the API is currently configured, changes to GatewayClass and its associated parameters have the potential to be very disruptive. A change to a GatewayClass parameter like `allowedRouteNamespaces` would potentially invalidate a large number of Routes for all Gateways using that class. Alternatively, a change to parameters associated with a GatewayClass could be backwards incompatible and require resources to be recreated. Here are some approaches that might help:

### Consider GatewayClass and params immutable
This would be straightforward to implement as an API and easy to understand. Unfortunately it would mean that even the smallest changes to a GatewayClass would require a new GatewayClass being created. This is especially problematic if we want to have consistent and meaningful GatewayClass names provided by implementations.

### Treat GatewayClass and params as templates
With this approach, GatewayClass params would be copied or applied to a Gateway on creation but then can change independently from the GatewayClass. A potential downside here would be that multiple Gateways would be associated with the same GatewayClass, the details could be significantly different if the GatewayClass changed between Gateway creations.

### Embed versions or revisions within a GatewayClass.
All existing revisions are immutable but new ones can be created. This would mean that a Gateway would need to reference both a GatewayClass and version. This would likely be complex to implement and could result in GatewayClasses with a large number of versions.

### Trust users not to break things
If we can't find a great way to limit potential disruptive changes here we could rely on better documentation around this functionality and accept that GatewayClass changes can potentially have disruptive consequences.

As a follow up note, this closely ties both GatewayClass and GatewayClass parameters together, even though this API can only directly control the GatewayClass resource. Parameters will be implementation specific by definition. I do think it would be helpful to at least provide guidance for how changes should be handled here.

**Comment by akutz** [comment]
What does `StorageClass` do?

**Comment by jpeach** [comment]
IIRC the original concept for using GatewayClass was that you would have a small number of classes pre-provisioned in the cluster. I think these were thought about as being largely static handles to infrastructure, so the default policy of "trust users to not break things" was more clearly a reasonable approach.

I think that there are a couple of dimensions to this problem.

1. Changes in parameters specified in the API. For any kind of class configuration that is defined in the API (i.e. fields specified through `GatewayClassSpec` that are not implementation-specific), I think that the API should specify how configuration changes should work, and the WG should think through the operational aspects.
The [production readiness questionnaire](https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md#production-readiness-review-questionnaire) has some good questions related to configuration changes.

2. Changes in controller-specific parameters. In this case, the API can really only provide suggestions to implementors. Which of the above options is desirable is very specific to the implementation and to the type of configuration change. For example, changing a default for connection timeouts seems like it should be allowed without requiring a whole new GatewayClass to be created. However, an implementation should not allow a change that would break existing gateways (follow the precautionary principle).

Without a stronger definition or assumption on what a GatewayClass is and how it behaves, I'm not sure that the first three suggestions are feasible. It's easy to think up hypotheticals that will support or refute any of these approaches, so adopting them constrains implementations. Of the first three, "Consider GatewayClass and params immutable" seems the most plausible.

**Comment by jpeach** [comment]
xref https://github.com/kubernetes-sigs/service-apis/issues/170

**Comment by hbagdi** [comment]
With #285 merged in, I think we have a better story now.
@robscott @jpeach Safe to close this one?

**Comment by robscott** [comment]
Agreed. I think we've mitigated this pretty well now.
