### ISSUE TITLE
Default PathType match should be prefix

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#254]
The current default behavior for PathType matching is `/` + `Exact`. I think it would be preferable to default to `Prefix` as the path type matching so by default a rule matches all requests. This would make it easier to initially set up a Gateway + Route combination that routed requests to all paths to a Service. I believe this would also more closely match user expectations when interacting with this API.

**Comment by jpeach** [comment]
Yep, I agree that exactly matching `/` is a pretty unintuitive default :)

**Comment by robscott** [comment]
Ignore this - just testing:

/milestone v1alpha1
