### ISSUE TITLE
Default HTTPRouteHost should be removed from HTTPRoute

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#255]
Since it will be common for Gateways to reference multiple Routes, there's significant potential for messy conflicts. If multiple Routes define a default there does not seem to be an obvious way to choose which default should be applied. This functionality can easily be replicated by a new route rule that matches `/` with a `Prefix` type, potentially the default if #254 makes sense. I think as we're approaching an alpha release we should attempt to remove any fields we don't need. This seems to qualify.

For reference, I'm talking about the field defined here: https://github.com/kubernetes-sigs/service-apis/blob/master/apis/v1alpha1/httproute_types.go#L27-L31

**Comment by hbagdi** [comment]
+1 to this change.

> If multiple Routes define a default there does not seem to be an obvious way to choose which default should be applied.

The default HTTPRouteHost is similar to Ingress v1's default backend, which has caused this exact problem for implementations which collapse multiple Ingress resources behind a single proxy/Gateway.
