### ISSUE TITLE
Potential Naming Collision on GatewayClass

### ISSUE THREAD

**Issue by freehan** [kubernetes-sigs/service-apis#26]
Multiple Gateway vendors can come up with the same name for their GatewayClass. For instance, popular names like `external-load-balancer`. That makes it quite possible to have naming collision in a cluster with multiple Gateway vendors. Meanwhile, k8s object name format is not as flexible as label. 

If the spec does not solve this and push this problem to the Cluster Admin, who needs to ensure there is no naming collision. Then I see the following implications:
- This sort of require vendors to handle flexible GatewayClass names. 
- This makes the Gateway bootstrapping more complex since vendor may not be able to provide static yamls. 
- This yeilds worse UX since the same Gateway vendor may have different GatewayClass names in different clusters. `foo` GatewayClass in cluster `a` vs.  `bar` GatewayClass in cluster `b`

Just one idea: Maybe force all Gateway vendor to use `GenerateName` on GatewayClass?

More ideas are welcomed or deem this as non-problem.

**Comment by youngnick** [comment]
The quote from the original API sketch I was thinking of was:

> Note that the community may converge around a common set of GatewayClass names with well-known meanings (e.g. x.net.k8s/from-internet, from-internal) to ease interoperability between platforms.

It feels to me that the current idea is that the GatewayClass name is largely descriptive, and Controller field inside the GatewayClass is intended to be the way a controller would find which GatewayClass objects it cares about (it's kind of a must-include label).

That is, when writing a controller, I don't really care about the name, I care about the value of `GatewayClass.Controller` - which should probably be set by convention to be a namespaced name like `ingresscontroller.company.com/name`.

Then, the vendors can provide namespaced GatewayClass objects (that is, `ingresscontroller.company.com/default-external` or whatever) in their static deployment YAMLs, but cloud providers can automatically provide the well-known names as part of cluster setup (so, un-namespaced `default-external`).

**Comment by bowei** [comment]
With Gateway class, it will be obvious to the admin that there is a conflict.
All implementations I know of can configure the prefix, not to mention people have used the java package like name (e.g. put your domain name in there), so this kind of thing does not happen very often.
