### ISSUE TITLE
Naming for Filters

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#265]
#249 introduces the Filters from the [Actions proposal ](https://docs.google.com/document/d/1SkTb6ECuiQiayvumdsZ3sxDcXD6cYs-DKB_C81Ajvh4/edit).

I've gone [back and forth](https://github.com/kubernetes-sigs/service-apis/pull/249#discussion_r466147246) on the name and we don't have a consensus on what the name should be.

Current proposals:
- Actions
- Addons
- Filters
- Plugins
- <your suggestion here>

The scope of this ticket is to land on a name that conveys the meaning we wish to achieve.

**Comment by jpeach** [comment]
Once way we could think about this is that an action terminates a chain of processing steps, where each processing step is a filter. That probably doesn't exactly match the configuration vocabulary of any of the proxies out there, but it is easy to explain.

**Comment by hbagdi** [comment]
> That probably doesn't exactly match the configuration vocabulary of any of the proxies out there

This is probably for the best.

**Comment by hbagdi** [comment]
I believe we are settled for now. Filters is the name we have settled on.

Please re-open if needed.
/close
