### ISSUE TITLE
Reconsider whether route actions are optional.

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#269]
In most (all?) of the route types, the action field is optional. It's not clear to me what a proxy should do if the action is omitted. Should it drop the traffic on the floor? Or should the action not really be optional?

**Comment by jpeach** [comment]
Applies to TCP, UDP and HTTP route types.

**Comment by hbagdi** [comment]
@robscott @jpeach We have gone back and forth on this one. #312 does some renaming and keeps the forward optional. I think we have found use cases like path/host redirection or HTTP redirection where it makes sense to have the forwarding target as empty.
I might be stating the opposite here, in which case, let's discuss more on this issue.
If not, we might able to close this issue.

**Comment by robscott** [comment]
I think we can close this issue now that #312 is in, feel free to reopen if we need more discussion here.

/close
