### ISSUE TITLE
Add MinItems annotation to route spec fields

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#271]
Most of the route types have an array (of rules or hosts) in their spec. We should add the `+kubebuilder:validation:MinItems` annotation to ensure that there is at least one entry in the top-level array.

**Comment by danehans** [comment]
similar issue: https://github.com/kubernetes-sigs/service-apis/issues/290
pr xref: https://github.com/kubernetes-sigs/service-apis/pull/336

**Comment by hbagdi** [comment]
I think Rob took this over so
/assign @robscott

**Comment by hbagdi** [comment]
This was fixed by #336.
/close
