### ISSUE TITLE
The 'Install' Make target Fails

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#287]
**What happened**:
I tried to run `make install` to install the CRD's according to the [dev guide](https://kubernetes-sigs.github.io/service-apis/devguide/) but it failed due to a missing make target.

**What you expected to happen**:
The CRDs to be installed.

**How to reproduce it (as minimally and precisely as possible)**:
run `make install`

**Anything else we need to know?**:
- This appears to be a regression due to https://github.com/kubernetes-sigs/service-apis/pull/275.
- https://github.com/kubernetes-sigs/service-apis/pull/284 is not enough to fix this issue.

/cc @hbagdi

**Comment by robscott** [comment]
Fixed by #288
/close
