### ISSUE TITLE
Clarify why we're using resource instead of kind in object references

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#293]
In my experience, references using a kind field are much more common than a resource field. I think this is going to result in a confusing user experience when getting started with this API. I'm not exactly sure where it belongs, but it would be good to document why we're doing this. As I understand it, the motivation comes from the 4th item in the list added here: https://github.com/kubernetes/kubernetes/pull/87459.

>The fields are both imprecise and overly precise.  Kind is not a precise mapping to a URL. This can produce ambiguity during interpretation and require a REST mapping.  In most cases, the dependency is on the group,resource tuple and the version of the actual struct is irrelevant.

**Comment by Miciah** [comment]
Related: https://github.com/kubernetes/community/pull/4705

**Comment by robscott** [comment]
I think my preference here is to switch back to using `kind` for object references until there's more consensus in the community around `resource`. This feels like something that will be easier for users to understand and lines up with how other references in Kubernetes already work. Interested in thoughts from others though. 

/cc @Miciah @bowei @danehans @hbagdi @jpeach

**Comment by jpeach** [comment]
Resource names are better for controller authors because you don't have to map from the kind to the resource. Users will probably be more familiar with the kind though.

**Comment by hbagdi** [comment]
+1 for `kind` because end users are more familiar with it.
