### ISSUE TITLE
Makefiles should be merged and cleaned up

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#295]
We currently have 2 makefiles, the standard `Makefile` and `kubebuilder.mk`. Although I think the original motivation was to keep consistent with kubebuilder, we've long since diverged from that pattern. This separation has resulted in a number of bugs that I think could've been easier to catch if we had a single, simpler makefile without all the cross references.

**Comment by jpeach** [comment]
Fixed in #301
