### ISSUE TITLE
Rename filters for user experience

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#307]
Filters are named such as 'requestHeader' and 'requestMirror' which make sense internally in the package but can be confusing for a user using our CRDs. 

More context: https://github.com/kubernetes-sigs/service-apis/pull/276#discussion_r485273444

**Comment by robscott** [comment]
@hbagdi are you still able to take this one?

**Comment by hbagdi** [comment]
Yes, apologies for the delay here.

I started making the patch for this but had second thoughts again.
In my thinking around this, the filters and their names are nouns and not verbs. Does it make sense to keep filters as nouns for our use case?

**Comment by danehans** [comment]
@hbagdi I submitted https://github.com/kubernetes-sigs/service-apis/pull/408 to fix this issue. Feel free to reassign yourself if you prefer your WIP PR over mine.

/assign
