### ISSUE TITLE
Standardize selector fields in the API

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#311]
**What would you like to be added**:

Label selectors are present in a few places in the API. The names are not defined as defined in upstream k8s APIs.
This issues stems from: https://github.com/kubernetes-sigs/service-apis/pull/285#discussion_r486661928

**Why is this needed**:
We should fix this for good user experience.

**Comment by robscott** [comment]
Prefer to have selector in name for fields.

**Comment by hbagdi** [comment]
@robscott Is there anything left to do here?

**Comment by robscott** [comment]
I don't think so, thanks!

/close
