### ISSUE TITLE
Provide Consistent Status Conditions Defaulting

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#313]
**What would you like to be added**:
Consistent status condition defaults for resources.

**Why is this needed**:
Improve user/dev experience. See https://github.com/kubernetes-sigs/service-apis/pull/308 for additional details.

**Comment by hbagdi** [comment]
I believe this has been now fixed with all our additions before v1alpha1 release.
Can you confirm and close this issue @danehans?

**Comment by danehans** [comment]
@hbagdi `RouteGatewayStatus` is missing a default status condition. https://github.com/kubernetes-sigs/service-apis/pull/528 fixes the issue.
