### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#333]
At a minimum, these examples should cover:

- [x] a simple GatewayClass, Gateway, HTTPRoute*
- [x] a Gateway that targets routes in multiple namespaces*
- [x] an example of TLS configuration
- [ ] working with other route types like TCPRoute or TLSRoute

We should try to embed existing examples from the repo instead of creating new ones.

`*` = must haves for v1alpha1 release

**Comment by hbagdi** [comment]
#427 accomplishes part of this.

**Comment by robscott** [comment]
#427 also potentially accomplishes 'a Gateway that targets routes in multiple namespaces' as well

**Comment by hbagdi** [comment]
> #427 also potentially accomplishes 'a Gateway that targets routes in multiple namespaces' as well

@robscott Do we need a separate guide from $427 for the multiple namespace point or can that box be checked off as well?

**Comment by robscott** [comment]
I'm on the fence. I think it's probably good enough to no longer block alpha, but we could probably use an example that actually showed different routes in different namespaces being targeted by the same gateway.

**Comment by hbagdi** [comment]
I was under the same confusion so errored on the side of having a new guide #452. PTAL.

**Comment by robscott** [comment]
I've dropped this down to priority/important-soon now that #452 has merged and all of our must haves for v1alpha1 are in.
