### ISSUE TITLE
HTTP Path/Header match order documentation

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#337]
**What happened**:

The documentation on most specific match for path and header matching within a hostname is missing.

**What you expected to happen**:

It should be documented.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Ingress v1 defines path matching priority and we should largely adopt it.
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#path-matching-semantics

**Comment by robscott** [comment]
@eth0xFEED Do you still have time to take this one on?

**Comment by eth0xFEED** [comment]
@robscott yes i am finally back from the long trip , will get this completed today 👍

**Comment by eth0xFEED** [comment]
From Miciah to Everyone: (6:31 PM)
 The current wording makes it difficult to figure out which of these wins:  * foobarbaz.foo.com/ * foobar.foo.com/foo * *.foo.com/foobar * *.foo.com/foobarbaz
