### ISSUE TITLE
Use a different branch for generated docs

### ISSUE THREAD

**Issue by aledbf** [kubernetes-sigs/service-apis#34]
and use a periodic Prow job to generate and push the content to the proper branch.

**Comment by bowei** [comment]
I tried this and the management was pretty complicated, especially when you are generating the docs and matching the docs up with the API types.
Can you sketch out how this would work?

**Comment by bowei** [comment]
I see -- you will only have the generated content via Prow. Seems ok, as long as it is automated.

**Comment by bowei** [comment]
Ping if anyone wants to pick this up.
