### ISSUE TITLE
OnlySameNamespace defautling to true needs to be reconsidered

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#343]
Currently inside the RouteNamespaces struct is as follows:

```go
// RouteNamespaces indicate which namespaces Routes should be selected from.
type RouteNamespaces struct {
	// NamespaceSelector is a selector of namespaces that Routes should be
	// selected from. This is a standard Kubernetes LabelSelector, a label query
	// over a set of resources. The result of matchLabels and matchExpressions
	// are ANDed. Controllers must not support Routes in namespaces outside this
	// selector.
	//
	// An empty selector (default) indicates that Routes in any namespace can be
	// selected.
	//
	// The OnlySameNamespace field takes precedence over this field. This
	// selector will only take effect when OnlySameNamespace is false.
	//
	// Support: Core
	//
	// +optional
	NamespaceSelector metav1.LabelSelector `json:"namespaceSelector,omitempty"`

	// OnlySameNamespace is a boolean used to indicate if Route references are
	// limited to the same Namespace as the Gateway. When true, only Routes
	// within the same Namespace as the Gateway should be selected.
	//
	// This field takes precedence over the NamespaceSelector field. That
	// selector should only take effect when this field is set to false.
	//
	// Support: Core
	//
	// +kubebuilder:default=true
	OnlySameNamespace *bool `json:"onlySameNamespace,omitempty"`
}
```

Currently this is in GatewayClass but is being moved to Gateway with #285.

The problem here is that we are resorting to `true` by default design with OnlySameNamespace being. True by default is usually not the most friendly API for the end user.

We should reconsider and make sure if we really want to do this.

**Comment by jpeach** [comment]
> The problem here is that we are resorting to true by default design with OnlySameNamespace being. True by default is usually not the most friendly API for the end user.

One of these fields has to be set. I don't know that there is a reasonable default for `NamespaceSelector`, so `OnlySameNamespace` has to be defaulted.

However, maybe we should default this at the usage site rather than in the type itself?
