### ISSUE TITLE
License Header Copyright

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#345]
I'm not sure if it makes a difference, but most projects in the kubernetes or kubernetes-sigs include `Copyright 2020 The Kubernetes Authors.` in the license header. This seems like something we should add unless it was intentionally excluded.

Example: https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/api/v1alpha3/condition_consts.go#L2

**Comment by danehans** [comment]
@andylibrian I started working on this issue last night. I should have assigned myself. PTAL at https://github.com/kubernetes-sigs/service-apis/pull/367.

**Comment by andylibrian** [comment]
No problem, @danehans. Thanks for letting me know.
