### ISSUE TITLE
Specify Printer Columns 

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#354]
We can use kubebuilder annotations to specify additional columns to print with `kubectl get` requests. Although many of our resources use structs and lists that don't work well with this, `GatewayClass.controller` is one great example of a field we should add. https://book.kubebuilder.io/reference/generating-crd.html#additional-printer-columns

**Comment by hbagdi** [comment]
@robscott Is it safe to close this now?

**Comment by robscott** [comment]
Yep, thanks!

/close
