### ISSUE TITLE
ListenerStatus.Port should probably be an int

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#357]
@danehans has pointed out that it is confusing for `ListenerStatus.Port` to be a string instead of an int. Currently it has this description:

```
	// Port is the unique Listener port value for which this message
	// is reporting the status. If more than one Gateway Listener
	// shares the same port value, this message reports the combined
	// status of all such Listeners.
```

@jpeach or @hbagdi can you think of any reason not to make this an int?

Context: https://github.com/kubernetes-sigs/service-apis/pull/336/files#r496830370

**Comment by hbagdi** [comment]
I don't recall why and I agree it should be an int32.

It could be something to do with DNS records but I really doubt that.
James might have more context on this one.

**Comment by jpeach** [comment]
Yeh this is a mistake. In the original commit, the protobuf type was `varint` and the Go type was `string`.
