### ISSUE TITLE
Should we have extension points in route Match?

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#359]
Do we have any concrete idea of how extension points within route match will be used?
I was trying to lay something out and it feels like having a custom XRoute resource will be more friendly than maintaining a HTTPRoute that points to a CRD which contains the match logic.
I think I'm missing something here so want to know more about the impetus of adding it.

Slack thread: https://kubernetes.slack.com/archives/CR0H13KGA/p1601413879036700

**Comment by jpeach** [comment]
One extension that users have asked for is to match on HTTP method.

**Comment by hbagdi** [comment]
As per WG discussions, we would like to keep this extension point in v1alpha1, gather feedback and then re-visit this question.

https://github.com/kubernetes-sigs/service-apis/pull/388 documents this.

/close
