### ISSUE TITLE
Discuss whether GatewayClass.Parameters should use RawExtension

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#36]
GatewayClass has a [Parameters](https://github.com/kubernetes-sigs/service-apis/blob/fdbee69573c9a7436bd1fe91530a00efeb3fb776/api/v1alpha1/gatewayclass_types.go#L44) field that is a TypedLocalReference to a separate, provider-specific configuration object.

On the last community call, I asked whether using a [RawExtension](https://godoc.org/k8s.io/apimachinery/pkg/runtime#RawExtension) for this field had been considered and promised to file an issue.

The primary benefit of using RawExtension for the Parameters is that the configuration will be visible inline in the relevant GatewayClass. Operators and vendors have fewer CRDs to install,  configure and reason about.

Based on the Cluster API experience, RawExtension has a number of [drawbacks](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20190709-cluster-spec-crds.md#motivation). I think that the main problem is the lack of flexibility that stems from the inability to use Kubernetes' built-in validation, versioning and conversion mechanics.

The StorageClass  [Parameters](https://github.com/kubernetes/kubernetes/blob/61d36e4a43b831f960b190b81d371cb33b5f20d1/pkg/apis/storage/types.go#L49) field takes a middle path by embedding a map of opaque strings for provisioner configuration.

**Comment by bowei** [comment]
I'm all for exploring different techniques here wrt to the API schema.
The claim here is that YAML can contain multiple objects using `---` which simplifies things.

The drawback is kubectl commands are more complex (pointer chasing) -- can be smoothed over w/ a kubectl plugin
Also, people have to come up with throw away names to link objects together.

Dealing w/ RawExtension for each of the providers will be like reimplementing the CRD logic but pushed to a webhook (assuming provider wants to have some form of synchronous validation)
Maybe there is a way to reuse the code?

**Comment by ironcladlou** [comment]
With referenced extensions, are there any concerns about update atomicity? Maybe not as much of an issue for something like GatewayClass, but consider the other extension points, like Route. For example, given a controller which needs to process Routes and make admission decisions, is it plausible that the Route extension must be considered in that decision? If so, does the referential decoupling introduce any challenges for the controller author given the objects might deserve to be treated logically as the same object?

**Comment by bowei** [comment]
This is definitely something to consider when breaking up resources. 

We should sketch out when this will/will not matter.

* it may not matter from use case perspective
* it is temporary (excluding control plane failures) to the point that users will not notice

One way to solve it would be pointer swapping a la concurrent data structures, but I'm hoping we don't have the need to do that...

**Comment by ironcladlou** [comment]
Great points. I don't have any specific concerns yet with the decoupling.

**Comment by hbagdi** [comment]
The working group seems to have leaning towards CRDs for this purpose and keep away from RawExtensions.

@jpeach  @ironcladlou @danehans @robscott Do we need more discussions here or is it okay to close this?

**Comment by bowei** [comment]
This feels like we can close this for now.
The topic will definitely come back up in feedback for v1alpha1.
