### ISSUE TITLE
Use go module compatible tag names

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/service-apis#392]
Currently the tag is v1alpha1-rc0. We should consider using go module compatible tags ideally for better integration there. I am not exactly sure what that would look like... one possible idea is

alpha1 = v0.1.1
alpha2 = v0.1.2
beta1 = v0.2.1
ga1 = v0.3.0 (or even v1 if we want to go down that route...)

**Comment by hbagdi** [comment]
Is there any documentation on how CRD versioning and Go module versioning should work together?
This proposal makes sense to me and we should certainly do it if it aligns well with upstream's guidance.

What should be the path forward here?
Is documenting this inside [release.md](https://github.com/kubernetes-sigs/service-apis/blob/master/RELEASE.md) sufficient?

cc @robscott @jpeach @danehans
