### ISSUE TITLE
Create an ingress implementation

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/service-apis#4]
Setting aside the [debate of the `default implementation` that was running in the mailing list](https://groups.google.com/d/msg/kubernetes-sig-network/ULr1a3XWYq0/N7ynBwswAgAJ),
I think that we should have an Ingress implementation so the community can start reporting feedback about the new Ingress API.

At the end of the day, you'll never know how this is going to evolve until is being used :smile:

**Comment by rikatz** [comment]
@aojea I'm just afraid of [this](https://pbs.twimg.com/media/DZ80C0CVoAEH1PQ.jpg) happening, but I also think we should at least provide a really simple ingress implementation to work only as a validation of user stories :)

**Comment by hbagdi** [comment]
@bowei Should we close this once we merge in https://github.com/kubernetes-sigs/service-apis/pull/87?

**Comment by aojea** [comment]
fair enough, community talked
/close
