### ISSUE TITLE
Gateway and HTTPRoute hostname matching should be more similar

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#410]
On Gateway we support the following HostnameMatchTypes:

- Domain
- Exact
- Any

On HTTPRoute we rely on wildcard for similar functionality (`*`, `*.foo.com`, and `foo.com` are all valid options).

**Comment by robscott** [comment]
I think there's a lot of overlap with this issue and #403. I think the pattern we've used for hostname matching in HTTPRoute is easy to understand and has the added benefit of being similar in nature to the Ingress host config. I propose replacing Gateway hostname config with a copy of the hostnames field on HTTPRoute. This field would behave in the same way as the field on HTTPRoute, if no hostnames were specified, all requests would match.

Although the current approach on Gateway is inherently more extensible, all of the existing match types can easily be communicated with wildcards. I haven't been able to think of any potential extension points where we might want to add more match types here, so the simpler structure seems like it would be preferable here.

**Comment by jpeach** [comment]
In general, I think that the HostnameMatchTypes is more explicit and hence easier to understand. For example, you can't easily know that `foo.*.example.com` is not a valid hostname match otherwise. Making the semantics explicit with an enum seems to me to be more in the spirit of the Kubernetes API.

**Comment by robscott** [comment]
`foo.*.example.com` would also be invalid for HTTPRoute:

>The wildcard character '*' must appear by itself as the first DNS label and matches only a single label

I think the wildcard pattern in general is fairly widely used and understood at this point. Here's what I think a transition would look like:

### Any
**Current**
```
hostname:
  match: Any
```

**Proposed**
No config needed


### Exact
**Current**
```
hostname:
  match: Exact
  name: foo.com
```

**Proposed**
```
hostname: foo.com
```

### Domain
**Current**
```
hostname:
  match: Exact
  name: foo.com
```

**Proposed**
```
hostname: *.foo.com
```


I'm definitely a fan of enums as I've introduced plenty of them here, but in this case I think it may add more complexity than necessary.

**Comment by robscott** [comment]
I've opened #416 to explore what this approach would actually look like.
