### ISSUE TITLE
Rename FilterTypeImplementationSpecific to FilterTypeExtension

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#413]
This would more clearly match the `ExtensionRef` field that is used for this filter type. (This feedback originally came from prealpha review).

**Comment by hbagdi** [comment]
@danehans, assigning you as you are on #408. Feel free to unassign.

/assign @danehans

**Comment by danehans** [comment]
xref: https://github.com/kubernetes-sigs/service-apis/pull/408
