### ISSUE TITLE
Require port to be specified whenever a Service is targeted

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#414]
From prealpha review - the following comment should be removed. 

```
// If the port is unspecified and a Service object consisting
// of a single port definition is the backend, that port will
// be used.
```

Port should always be specified when a Service is the target resource. Leaving this in would risk significant breaking changes if a second port was added to a Service.

**Comment by robscott** [comment]
For HTTPRoute we may want to default port to 80.

**Comment by hbagdi** [comment]
What are the downsides of always requiring a port?

It helps with debugging where a Gateway and Route resource tell you all you need to know about the network path of a request.

**Comment by robscott** [comment]
I can't think of many downsides other than one more field to specify in manifests. I think requiring a port would be a good improvement to the API, especially if we could have a sensible default of 80 on HTTPRoute.

**Comment by hbagdi** [comment]
I see. I think I understand what you mean. Let me push up a patch for this now and we can take it from there.
