### ISSUE TITLE
Add a way for TCPRoute, TLSRoute, and UDPRoute to match all requests

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#415]
From the prealpha review: We have not clarified what happens when no matches are specified. It may make sense to use an enum here that supported the following options:

- All
- ExtensionRefs
- None

This could get confusing because we support multiple match structs here. Alternatively we may want to specify that if no matches are specified, all requests should match.

**Comment by robscott** [comment]
@hbagdi or @danehans Are you still able to take this one on?

**Comment by danehans** [comment]
+1 specifying that if no matches are specified, all requests should match. This approach provides consistency with default matching of other API fields and with Ingress hostname matching. This issue does not address TLSRoute though.

**Comment by hbagdi** [comment]
> @hbagdi or @danehans Are you still able to take this one on?

Removed myself from Assignee list a while ago because had too much on the plate.
