### ISSUE TITLE
Reuse as much as possible between HTTPRouteForwardTo and RouteForwardTo

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#440]
There's a lot of overlap in these two types, and so far they've both been entirely duplicated. I believe the only difference is that `HTTPRouteForwardTo` includes filters.

**Comment by hbagdi** [comment]
We decided to not do this: https://github.com/kubernetes-sigs/service-apis/pull/476#issuecomment-777028096

/close
