### ISSUE TITLE
Change GatewayClass Condition to `Accepted`

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/service-apis#465]
**What would you like to be added**:

Currently, GatewayClass' `status` stanza has only one Condition type explicitly laid out in the type files - `InvalidParameters`. This makes sense as a coordination mechanism for controllers that actually use the `spec.parametersRef` field, but is confusing for ones that don't.

**Suggested change**:
We change the standard condition for GatewayClass to `Accepted`, with `InvalidParameters` as a sample *reason* for it to be false. This condition then will be the default, with its status set to `Unknown` until a controller sees the object, at which time the controller *must* update the Condition `status` to `true` or `false`.

I've got a PR for this change ready to go.

**Comment by jpeach** [comment]
Routes use "Admitted", which is very similar.

**Comment by youngnick** [comment]
We should use `Admitted` then, agreed.
