### ISSUE TITLE
Add Destination Service Port Selection to Route APIs

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#48]
**What would you like to be added**:

A Kubernetes `Service` has the ability to expose multiple ports. However, a `HTTPRoute` provides no ability to specify the destination service port that should be used to forward traffic. `HTTPRoute` should be updated to allow the destination service port to be specified.

**Why is this needed**:

As a developer, I need the ability to forward ingress traffic to a specific destination port on a service that exposes multiple ports.

/kind enhancement

/cc @bowei

**Comment by bowei** [comment]
/kind/design

**Comment by bowei** [comment]
I put kind/design -- apparently kind/enhancement doesn't exist?

**Comment by bowei** [comment]
Ahh -- this is probably just an oversight when we were throwing the initial API spec together. What we have should be the same in behavior as the current Ingress

**Comment by danehans** [comment]
Using k8s enhancements as the reference model, enhancements should be labeled as `kind/feature`.

/kind/feature

**Comment by danehans** [comment]
> I put kind/design -- apparently kind/enhancement doesn't exist?

@bowei after a quick read of the [labels doc](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#kind/feature), it appears enhancements should be labeled as `kind/feature`. This is the approach I took in https://github.com/kubernetes-sigs/service-apis/pull/46.

**Comment by bowei** [comment]
ok fixed

**Comment by danehans** [comment]
> What we have should be the same in behavior as the current Ingress

@bowei I think it may be more complicated with the new API's due to `ForwardTo` of `HTTPRouteAction` being a `ObjectReference` instead of a `corev1.Service` type. For example, what if `ForwardTo` references another `HTTPRoute`?

/cc @youngnick

**Comment by jpeach** [comment]
Most (all?) ingress controllers have some mechanism to specify the target port for upstream services (either annotation or in-band to a custom CRD). Maybe we could do a prior art survey to inform a spec proposal?

**Comment by danehans** [comment]
> Most (all?) ingress controllers have some mechanism to specify the target port for upstream services 

@jpeach Our challenge is that `HTTPRouteAction` can forward to non-Service objects. Here are a couple ideas for supporting Services that specify multiple ports:

#### Add `ServicePort` property to the `HTTPRouteAction` API type.
```
import k8s.io/apimachinery/pkg/util/intstr

// HTTPRouteAction is the action taken given a match.
type HTTPRouteAction struct {
	// (Existing fields omitted, only newly proposed fields are visible)
	...
	// ServicePort specifies the destination port to use when ForwardTo is
	// a Service object. ServicePort can be the port name or port number of
	// the ForwardTo Service. If unspecified and the ForwardTo Service consists
	// of a single port definition, that port will be used. If unspecified and the
	// ForwardTo Service consists of multiple port definitions, the Service port
	// that matches the request's destination port will be used. If a match can't
	// be found, an error will be reflected in status. ServicePort is ignored for
	// ForwardTo references other than a Service object.
	//
	// Support: Core
	//
	// +optional
	ServicePort *intstr.IntOrString
}
```
#### Add `Port` property to the `HTTPRouteFilter` API type.
```
// HTTPRouteFilter defines a filter-like action to be applied to
// requests.
type HTTPRouteFilter struct {
	// (Existing fields omitted, only newly proposed fields are visible)
	...
	// Port defines a filter-like action to be applied to the TCP port
	// number of a matched request.
	//
	// Support: Core
	//
	// +optional
	Port HTTPRouteFilterPort

// HTTPRouteFilterPort defines a filter-like action to be applied to requests.
type HTTPRouteFilterPort struct {
	// DestinationNumber specifies the destination port number to use in
	// the request. If unspecified, the matching request's destination
	// port is used.
	//
	// Support: Core
	//
	// +optional
	DestinationNumber *int
	//
	// Does a use case exist for SourcePort, DestinationName, etc.?
```
/cc @robscott @Miciah

**Comment by jpeach** [comment]
> > Most (all?) ingress controllers have some mechanism to specify the target port for upstream services
> 
> @jpeach Our challenge is that `HTTPRouteAction` can forward to non-Service objects. Here are a couple ideas for supporting Services that specify multiple ports:

Sure, but it doesn't matter what the target object is, the principle is the same

**Comment by robscott** [comment]
Thanks for following up on this issue @danehans! If possible, I'd prefer to keep our approach as simple as possible here. I'd be open to just using an int32 as the target port here as that seems like it would work universally with anything we reference. With that said, the precedent already set by Ingress is to [use intstr](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/networking/v1beta1/types.go#L260), so that may be the least controversial option here. Either way, I think we should add something here soon because it's a significant gap in the current API.

**Comment by aledbf** [comment]
> With that said, the precedent already set by Ingress is to use intstr, so that may be the least controversial option here.

can `int32` be used instead of `intstr`?. 
Using an ingress controller as an entry point to a service mesh is a common use case and mixing types is an issue xref: https://github.com/linkerd/linkerd2/issues/4211

**Comment by danehans** [comment]
> can int32 be used instead of intstr?

@aledbf https://github.com/kubernetes-sigs/service-apis/pull/138 uses int32.
