### ISSUE TITLE
The maximum limitation for HTTPRouteForwardTo is too small

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/service-apis#481]
**Why is this needed**:

- The maximum limit of `httproutes.spec.rules.forwardTo` is only `4` as per [httproute_types.go#L205-L206](https://github.com/kubernetes-sigs/service-apis/blob/4455c32ed47a8b47f686d2c5c64aeff9b6798dcd/apis/v1alpha1/httproute_types.go#L205-L206).
- For example, Knative currently verfies [10 traffic split](https://github.com/knative/networking/blob/28c37e3cbe53b06b2471c4231c347a95cec8e019/test/conformance/ingress/visibility.go#L119) but it will not work when we migrate to service-apis. (I think Istio, Contour and other ingresses also do not have the limitation on their routing feature now.)
- I personally don't know any actual users who is doing traffic split more than `4` but I am worried this limitation because we will not be able to support what we can support it now.

**What would you like to be added**:

- Sufficient limitation like `MaxItems=16` (MaxItems=16 is used in relatively many other fields) is used.
- Or the maximum limitation could be decided by each Ingress providers.

**Comment by robscott** [comment]
Hey @nak3, thanks for reporting this! Our goal was to start with relatively low limits that each implementation could support and then expand from there. We're really just trying to avoid unbounded lists wherever possible. Do you know of any upper limits as far as what Knative or other implementations might be capable of? Is a traffic split between more than 4 targets a common or critical use case? (Not saying we shouldn't increase this limit, just trying to understand the scale of this issue and what a reasonable upper limit might be).
