### ISSUE TITLE
Better modeling of a "virtual host"

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/service-apis#49]
This has come up in discussions about the split in functionality between Gateway and the set of Routes attached to a Gateway. See the meeting notes starting here: 

The purpose of the split resource is model different permissions and delegation regarding assembly of a LB vs the application author (see "resource model" here: https://kubernetes-sigs.github.io/service-apis/concepts).

As currently sketched, we have [virtualhost](https://httpd.apache.org/docs/2.4/vhosts/examples.html) definitions in the Route while protocol e.g. TLS termination settings are determined in the Gateway. This presents an interesting twist regarding TLS certificates: it is part of a lower-level protocol layer that ties into higher layer HTTPx protocols. Also there are use cases such as support for TLS byte streams or TLS-based opaque routing.

At the same time, we need to be careful about allowing the admin persona control over security related policies, e.g. which certificates can/cannot be attached to a given gateway.

* If TLS settings are specified at the Gateway level and virtualhost routing at the Route level, can we reduce the verbosity associated with this setup? This is information that needs to be consistent split between two resources.
* Should the owner of a application (e.g. Route) be able to specific their own certificates and TLS policies? If this is allowed, how will this ability be controlled in a safe and effect way? OR does this just mean we should give the application developer access to the Gateway resource, as they are going to be introducing certificates anyway. 

Proposal to get clarity:
* Sketch out permissions models regarding what each permissions we see giving the different personas in each case.
* Sketch out model with TLS stream and HTTPS models.

**Comment by danehans** [comment]
API implementation example for adding tls config in routes: https://github.com/kubernetes-sigs/service-apis/pull/35

**Comment by danehans** [comment]
> Sketch out permissions models regarding what each permissions we see giving the different personas in each case.

@bowei I've started working on this. PTAL at [this drawing](https://docs.google.com/drawings/d/1zcu_UJInJ3JhIAgCFwqhD2a3RnUal2EkwKaP80k0TZM/edit?usp=sharing), which models TLS Config in `HTTPRoute` for the "Developer" persona. Let me know if I'm heading in the right direction. If so, I will expand to cover the different scenarios.

**Comment by danehans** [comment]
> OR does this just mean we should give the application developer access to the Gateway resource, as they are going to be introducing certificates anyway.

If we give the Developer persona access to a `Gateway`, I question whether a separate resource (i.e. `HTTPRoute` should still exist.

**Comment by danehans** [comment]
xref tls termination policy: https://github.com/kubernetes-sigs/service-apis/issues/52

**Comment by jpeach** [comment]
>  I've started working on this. PTAL at this drawing, which models TLS Config in HTTPRoute for the "Developer" persona

@danehans That diagram doesn't mention TLS config, so maybe I am missing some context?

**Comment by hbagdi** [comment]
https://github.com/kubernetes-sigs/service-apis/pull/193 addresses some concerns in this issue.

**Comment by costinm** [comment]
I think it's a great change ! AllowedHostname[] is reasonable - it allows the domain owner to create a Gateway, set the cert and restrict which namespaces can use the domain. Assuming https://github.com/kubernetes-sigs/service-apis/issues/197 is addressed ( i.e. allow using the namespace name ) - it seems viable.

I'm not very sure the usability of having port 443 and port 80 is great - it is extremely common to have the same hostname on both http and https ( with http doing redirect usually ). In this model, user will have to type every hostname 2x - once for the port 80 and once for port 443. 
Instead the list of hostnames (hostname match or allowedhostnames) could be in Gateway at the top level, and can optionally include a port. 

example:

```
Gateway:
   allowedHostnames:
     - www.example.com
     - admin.eample.com:443
     - *.test.example.com

   listeners:
     - port: 80
     - port: 443
        tls: 
          ....
```

**Comment by hbagdi** [comment]
> In this model, user will have to type every hostname 2x - once for the port 80 and once for port 443.

Providing hostnames at the gateway layer implies that if you are mixing L4 and L7 listeners, and if there is no way to decide filter hostnames at a per listener level, that would lead to users configuring multiple Gateways. YAML's referencing (`*` and `&`) capabilities could help somewhat?

**Comment by hbagdi** [comment]
@bowei @jpeach @robscott It seems we have settled on this one, can we close this one?

**Comment by jpeach** [comment]
Yup, I'm happy yo close this out.

**Comment by hbagdi** [comment]
Closing this since we have consensus on this. If you disagree, please feel free to re-open.
/close
