### ISSUE TITLE
Remove namespace from examples

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#498]
**What would you like to be added**:

- Remove namespace from example manifests (unless the namespace is relevant to the example).
- Update docs if required due to this change

**Why is this needed**:

It makes it harder for some tools to apply examples to a namespace other than default.
See: https://github.com/kubernetes-sigs/service-apis/pull/496#discussion_r539069054

**Comment by stevesloka** [comment]
I can take this one. 

/assign
