### ISSUE TITLE
Consider naming `TypedLocalObjectReference` fields `fooRef`

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#50]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions

> The name of a field referring to another resource of kind Foo by name should be called fooName. The name of a field referring to another resource of kind Foo by ObjectReference (or subset thereof) should be called fooRef.

Following this recommendation would replace `Extension` with `ExtensionRef`, but it would also replace `ForwardTo` with something less wieldy (maybe `TargetRef`). So maybe it's better not to follow this convention in all cases.

**Comment by bowei** [comment]
This reminds me of "Hungarian notation". I think we should try to make it align, but use common sense.

**Comment by Miciah** [comment]
While we consider the naming, we should also consider using custom types instead of `ObjectReference` and `TypedLocalObjectReference`, per the recommendation in https://github.com/kubernetes/kubernetes/pull/87459.  (Let me know if you would prefer a separate issue for the type issue.)

**Comment by bowei** [comment]
Let's open a PR against the developer guide section of the docs and continue the discussion there.

**Comment by Miciah** [comment]
Opened #73 to replace types.

**Comment by robscott** [comment]
I believe this was fixed by #73, feel free to reopen if I missed anything.
