### ISSUE TITLE
Execution order of []HTTPRouteFilter

### ISSUE THREAD

**Issue by tokers** [kubernetes-sigs/service-apis#500]
**What would you like to be added**:

For now, the order of HTTPRouterFilter is not specified according to the document.

>  Filters define the filters that are applied to requests that match this rule.
>
> The effects of ordering of multiple behaviors are currently unspecified. This can change in the future based on feedback during the alpha stage.

What do you think of adding the built-in priority of HTTPRouteFilter, each filter will be assigned a priority which decides their running order.

**Why is this needed**:

Some filters, like Auth, should be executed firstly, but if the admin put them latter in the filter list, then these Auth filters might influenced even lost their functions.

**Comment by robscott** [comment]
Would it be reasonable to say something like the following?

```
Where possible, filters should be implemented in the order they are specified.
```

**Comment by danehans** [comment]
A consensus was achieved during the 12/16/20 community meeting to not add an ordering field and leave the HTTPRouteFilter documentation general (i.e. https://github.com/kubernetes-sigs/service-apis/issues/500#issuecomment-745705314) until implementations gain traction.

**Comment by tokers** [comment]
> A consensus was achieved during the 12/16/20 community meeting to not add an ordering field and leave the HTTPRouteFilter documentation general (i.e. [#500 (comment)](https://github.com/kubernetes-sigs/service-apis/issues/500#issuecomment-745705314)) until implementations gain traction.

Thanks for you reply, I see it.
