### ISSUE TITLE
Improve the CRD Installation Experience

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#502]
**What would you like to be added**:
An easier way to install Service APIs CRDs, including a specific version. The current user experience is:

```
kubectl kustomize "github.com/kubernetes-sigs/service-apis/config/crd?ref=master" \
| kubectl apply -f -
```

**Why is this needed**:
Currently, the installation experience has the following limitations:

1. kustomize is required
2. Only the master branch is referenced.

Should a single yaml manifest get rendered so users can simply kubectl https://kubernetes-sigs.github.io/service-apis/release/${VERSION}/service-apis-crds.yaml. This could be accomplished with something like:
```
kustomize build config/crd > examples/crd/${VERSION}/service-apis-crds.yaml
```

If more trickery is needed or we need to keep the CRDs separate, we can use an installer script similar to Istio. Thoughts?

/cc @robscott @bowei @hbagdi

**Comment by howardjohn** [comment]
Isn't kustomize built-in to kubectl so everyone should have it since 1.13 if I recall right. You also can reference tags like `kubectl kustomize "github.com/kubernetes-sigs/service-apis/config/crd?ref=v0.1.0-rc2" | kubectl apply -f -`

**Comment by danehans** [comment]
If https://github.com/kubernetes-sigs/service-apis/issues/502#issuecomment-743497074 is correct, maybe this is a docs update to set the version for `ref=`.
