### ISSUE TITLE
Update gen-crd-api-reference-docs dependency

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/service-apis#505]
Once https://github.com/ahmetb/gen-crd-api-reference-docs/pull/29 merges, we need to switch back to using that version instead of @jpeach's fork. We originally diverged due to https://github.com/kubernetes-sigs/service-apis/pull/503.

**Comment by hbagdi** [comment]
This was fixed in https://github.com/kubernetes-sigs/service-apis/pull/513.
/close
