### ISSUE TITLE
Backend Object Traffic Manipulation

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#58]
**What would you like to be added**:
Support for manipulating post-routed requests among multiple backend objects:

- [ ] Weight or percentage-based traffic splitting among multiple endpoints of a `Service`.
- [ ] Label-based traffic splitting among multiple endpoints of a `Service`.
- [ ] Weight or percentage-based traffic mirroring among multiple endpoints of a `Service`.
- [ ] Label-based traffic mirroring among multiple endpoints of a `Service`.
- [ ] Setting connection timeouts, retires, etc..

**Why is this needed**:
Provide more fine grained control over forwarding routed requests to backend objects.

A good reference model is Istio's [HTTPRoute](https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRoute).

**Comment by danehans** [comment]
In support of https://github.com/knative/serving/issues/6593 and other traffic splitting use cases (i.e. Contour, Istio, etc.).

/cc @youngnick

**Comment by hbagdi** [comment]
+1

There are two features that are require:
- *Traffic split*: This is doing a split of live traffic among different versions of the service, sometimes referred to as canary testing as well.
- *Traffic shadowing*: A subset of Requests is duplicated and sent to another backend. The response from the duplicated requests is discarded.

We should target to achieve both of these under the same umbrella feature.

**Comment by danehans** [comment]
@hbagdi I updated the issue title and description based on your feedback.

**Comment by evankanderson** [comment]
@tcnghia (for tracking)

**Comment by tcnghia** [comment]
@danehans @hbagdi what is the status of this issue?  thanks

**Comment by hbagdi** [comment]
@tcnghia WIP at https://github.com/kubernetes-sigs/service-apis/pull/57

**Comment by danehans** [comment]
Note that https://github.com/kubernetes-sigs/service-apis/pull/57 only addresses "Weight or percentage-based traffic splitting among multiple endpoints of a `Service`."
