### ISSUE TITLE
Route Admission Policy

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#60]
**What would you like to be added**:
The ability to share the same hostname across multiple routes in different namespaces.

**Why is this needed**:
Administrators and application developers would like to run applications in multiple namespaces with the same domain name. This is for organizations where multiple teams develop microservices exposed on the same hostname.

Allowing hostname claims across namespaces should only be enabled for clusters with trust between namespaces, otherwise a malicious user could take over a hostname. This should therefore be an "opt-in" feature.

**Comment by danehans** [comment]
xref'ing https://github.com/kubernetes-sigs/service-apis/issues/49 as this may have ties to spec'ing vhost.

**Comment by danehans** [comment]
/assign @bowei 

cc: @Miciah @ironcladlou

**Comment by Miciah** [comment]
The main use-case for having multiple routes with the same host name is when the routes have different match rules.  For example, one route matches `www.example.com/app1` and another route matches `www.example.com/app2`.

**Comment by danehans** [comment]
Expanding on the example in https://github.com/kubernetes-sigs/service-apis/issues/60#issuecomment-581565939:

App "foo.example.com" is made up of several app services, each running in a different namespace. For example /login service runs in ns foo-app-login and /content is the main frontend service in ns foo-app-main. Currently, `xRoute` forwardTo is a "local" object reference so these services must be in the same ns as the `xRoute`.

**Comment by youngnick** [comment]
xref #102
