### ISSUE TITLE
Add Domain Support

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#62]
**What would you like to be added**:
The ability to associate a DNS domain to an instance of `Gateway`.

**Why is this needed**:
1. Allows `httproute.spec.hosts[x].hostname` to be optional. Gateway implementations can use a `Gateway` or `GatewayClass` config directive such as the following to generate the hostname for an `HTTPRoute`:
```
	// Domain is the DNS name serviced by the Gateway and is used to:
	//
	// 1. Configure DNS records (optional).
	//
	// 2. Generate a default certificate. The certificate will be valid
	//    for domain and its subdomains.
        //
	// 3. Generate httproute.spec.hostname if unspecified in the form of:
        //    <route_name>-<route_namespace>.<domain>
	//
	// Domain must be unique among all Gateways and cannot be updated.
	//
	// +required
	Domain string `json:"domain"`
```
2. `Domain` can be used to generate route certificates or a default wildcard certificate for a gateway listener.

## Reference Implementations ##
- Contour's [fqdn](https://github.com/projectcontour/contour/blob/master/apis/projectcontour/v1/httpproxy.go#L100)
- OpenShift's [ingresscontroller](https://github.com/openshift/api/blob/master/operator/v1/types_ingress.go)

/cc @bowei

**Comment by hbagdi** [comment]
With changes from #193 merged in, can this be closed?
