### ISSUE TITLE
Add a custom label for user stories

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#64]
**What would you like to be added**:

A custom label `kind/user-story` or `kind/use-case` to distinguish issues that capture Ingress V2 use case descriptions.

**Why is this needed**:

As we migrate user stories from the [doc](https://docs.google.com/document/d/1OAzVO0HfmF4qD8AW41_eeUY0KP6xjqghusUVwhp4BNg) to issues, it would be useful to be able to distinguish them in the issue list. The `kind/feature` label is currently being used, but that is also used for features in general, so there's no way to tell user stories from other types of feature without reading them.

**Comment by jpeach** [comment]
Label management info: https://github.com/kubernetes/test-infra/tree/master/label_sync

I think the patch would look thusly:
```
diff --git label_sync/labels.yaml label_sync/labels.yaml
index 35a1b8cfb..5065ad83f 100644
--- label_sync/labels.yaml
+++ label_sync/labels.yaml
@@ -1373,3 +1373,10 @@ repos:
         target: both
         prowPlugin: label
         addedBy: anyone
+  kubernetes-sigs/service-apis:
+    labels:
+      - color: c7def8
+        description: Categorizes an issue as capturing a user story
+        name: kind/user-story
+        target: issues
+        addedBy: humans
```

The color here is the same as for `kind/feature`.

**Comment by bowei** [comment]
Looks ok to me, we will have to transition the labels after.

**Comment by robscott** [comment]
@jpeach We agreed that this makes sense on todays Service APIs call.
