### ISSUE TITLE
Use case: self-service TCP proxy

### ISSUE THREAD

**Issue by rosenhouse** [kubernetes-sigs/service-apis#66]
**What would you like to be added**:
As a [Cluster Operator](https://kubernetes-sigs.github.io/service-apis/concepts/#roles-and-personas) I would like to enable the [Application developers](https://kubernetes-sigs.github.io/service-apis/concepts/#roles-and-personas) on my cluster to self-service reserve a TCP port from a range on a shared Load Balancer, and have that port forward to a workload.

**Why is this needed**:
HTTP and SNI protocols contain a virtual host header that facilitates routing to many workloads from a single shared TCP port (e.g. 80 or 443).  However, many legacy application protocols do not support virtual-hosting.  They are effectively an opaque TCP stream, so different services cannot be provided on the same public TCP port.

Service `type=LoadBalancer` would work in some cases, but has drawbacks:
- public IPs / public LoadBalancers may be prohibitively expensive at scale
- Support for LoadBalancer is present on all major public clouds, but isn't well-supported on all infrastructure, e.g. on-premise setups.  (Solutions like MetalLB are have an unclear status, and the *cluster operator* may not be able to do the necessary BGP and ARP-level network integrations in the data center).

Service `type=NodePort` also would work in some cases, but:
- doesn't publish the preferred IP/hostname for clients to use, and nodes may be not reachable by clients.
- doesn't benefit from the extensibility supported in the service-api, e.g. GatewayClass, traffic-split, etc.

However, cluster operators may be able to do some upfront work to get a single shared Load Balancer set up, and have a range of ports (e.g. 2000-11999) available for use by an ingress controller.  They would like to tell the ingress controller what range is available for use, and then enable Application Developers to claim ports from this range.

**Example workflow**
- A cluster operator would configure a resource to define a "pool" of TCP ports that are available to be claimed by application developers on a particular load balancer, e.g. `2000-11999`
- An application developer configures a resource that specifies a claim to a port and defines routing rules to backend workloads (e.g. core Service).  The resource may explicitly specify a preferred port number, or may omit it and the controller will assign a free port from the pool.  This smells like PersistentVolumeClaim and PersistentVolume.

**Other thoughts**
- UDP too?

**References:**
- Looks like the [Port Control Protocol RFC](https://tools.ietf.org/html/rfc6887) (hat tip to @danderson for pointing this out on twitter a few weeks back)
- Workflow is [supported on Cloud Foundry](https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#create-route-with-port).

**Comment by hbagdi** [comment]
@rosenhouse Can you take a look at the schemas for Gateway and TCPRotue resources? I believe the schema now allows for the use case described above.

**Comment by rosenhouse** [comment]
Cool, so my read of the specs (and a bit of confirmation on slack) is that yes, it would be possible to to orchestrate this, by building a higher-level controller that works with Service APIs.

For example, you give it a Gateway that it would "own" and a pool of ports it can allocate from.  Then it can watch for `TCPRoute` resources that aren't already bound to a Gateway, and: reserve a port from the pool, add a listener to the Gateway and have the listener select that TCPRoute.

**Comment by hbagdi** [comment]
Yes, that sounds right.
Closing this then.
/close
