### ISSUE TITLE
Clarify uniqueness constraints of httproutehost.hostname field

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes-sigs/service-apis#67]
**What would you like to be added**:

This issue is to try and define what, if any, uniqueness constraints should be defined for the [httproutehost.hostname field](https://github.com/kubernetes-sigs/service-apis/blob/master/api/v1alpha1/httproute_types.go#L36). 

The conversation started in [service-apis/pull/43/files#r367088840](https://github.com/kubernetes-sigs/service-apis/pull/43/files#r367088840) and seems orthogonal to the question about whether the hostname field should be plural.

**Why is this needed**:

The decision one way or another will have a potentially significant impact on implementors depending on the necessarily complexity associated with whatever constraints are required by the API.

**Comment by jpeach** [comment]
/remove-lifecycle rotten

This probably still needs some explanatory text.

**Comment by hbagdi** [comment]
There seems to be consensus that `hostname` field is not going to be unique.
There are conflicts possible at the Gateway listeners level and guidance for that has been added already.
Closing this but please re-open if needed.
/close
