### ISSUE TITLE
Spec requirements on certificate secrets

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#74]
There are a number of interoperability questions about the use of secrets to store TLS keys and certificates. It may be helpful to have consolidated language to address these.

- If it is a `TypedLocalReference`, what kinds must an implementation support?
- Is the secret type required (e.g. `v1.SecretTypeTLS`)
  - If so, spec required types for server and client certificates, keys and CA bundles
- Can secret data have multiple keys?
- Are any specific secret data keys required?
- What secret data formats must be supported? Only PEM?
- Are multiple items allowed in a single secret data value (i.e multiple PEM blocks)
- How items can be combined (e.g. is it OK to have key, cert and CA bundle all in one secret)

There may be existing certificate specs that we can incorporate by reference; we could also choose to punt this issue to implementations.

**Comment by bowei** [comment]
For sure supported:

1. Kubernetes Secrets, as used today by Ingress V1; let's take what is the current requirements from that and pull it here. This is easy for users to interoperate with and we have a solid basis to go from.

It's a typed ref for extension to other systems. The easiest thing to do here is to make anything else `Support: custom` and put this into the backlog.

**Comment by hbagdi** [comment]
I believe this is all documented in Go doc comments. Is it safe to close this?

**Comment by robscott** [comment]
I believe so as well, feel free to reopen if not.
