### ISSUE TITLE
protos: make the package sigs.k8s.io instead of k8s.io

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/service-apis#79]
https://github.com/kubernetes-sigs/service-apis/pull/30 introduce a workaround for protobuf resolution, requiring the package to be k8s.io instead of sigs.k8s.io. We should see if we can get around this and change the package name

**Comment by bowei** [comment]
is this still relevant"? we've migrate this to networking.x-k8s.io which should be different than networking.x.k8s.io

**Comment by howardjohn** [comment]
We got rid of protos
