### ISSUE TITLE
[Question] Listener TLS

### ISSUE THREAD

**Issue by aledbf** [kubernetes-sigs/service-apis#8]
Can we avoid the use of [`map[string]string`](https://github.com/kubernetes-sigs/service-apis/blob/master/api/v1alpha1/gateway_types.go#L146) and use `core.TypedLocalObjectReference`?

**Comment by rikatz** [comment]
Could only find this here: https://github.com/kubernetes-sigs/service-apis/blob/master/api/v1alpha1/gateway_types.go#L177

Was the file changed from when you found it to now, removing those map[string]string?

**Comment by ironcladlou** [comment]
This issue appears to be resolved on master.

**Comment by bowei** [comment]
Can we dupe this w/ the general extensions discussion or we want to keep this open separately (this issue will be pretty much stale)

**Comment by bowei** [comment]
This seems to be no longer relevant. Please reopen if you think this has not be resolved.

/close
