### ISSUE TITLE
What is the intention of the controllers?

### ISSUE THREAD

**Issue by ibuildthecloud** [kubernetes-sigs/service-apis#82]
I see this project already has a set of boilerplate controllers that seems to be no-op. What is the intention of the controllers.  Can I propose that this project focus just on the API and only as a last resort create controllers. I think if you design with that mindset you will have a stronger API.  In the end there will most likely be one dominate implementation, but that should minimally be in a separate repo from "service-apis."

Related but different, a validating webhook would make sense to be in scope for this project to ensure the types are sane.

**Comment by bowei** [comment]
The controllers are generated automatically by the kubebuilder framework.
It is not in the plan currently to create a "default" controller here.

The controller stubs will likely be used to test the validation logic and support library code, though.

**Comment by bowei** [comment]
So the answer to your question is yes, we are focused on the API here, not a controller.

**Comment by bowei** [comment]
I added your question to the FAQ, otherwise not sure how to close this issue...

**Comment by ibuildthecloud** [comment]
Thanks!
