### ISSUE TITLE
Expand the definition of a Route

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/service-apis#85]
**What would you like to be added**:
Currently a `Route` is defined in the `Gateway` API type as:
```
// Routes associated with this Gateway. Routes define protocol-specific routing to backends (e.g. Services).
```
**Why is this needed**:
Ambiguity exists on what a route means. The field should be well defined since it's a key concept. See https://github.com/kubernetes-sigs/service-apis/pull/71/files#r378628721 for additional background.

/assign @bowei
/cc @jpeach @ironcladlou @Miciah

**Comment by danehans** [comment]
A possible route definition:
```
// A route allows a cluster operator to expose a service by externally-reachable URL,
// load balance traffic, terminate SSL/TLS, and offers name-based virtual hosting.
// A route supports a reference to an HTTPRoute, TCPRoute or TrafficSplit resource.
// Routes can be chained together to form a hierarchy of actions to perform against
// a request.
//
// If unspecified, no routes will be associated to the Gateway.
//
// Support: Core
//
// +optional
```

Should a gateway bind to all or no routes by default? xref: https://github.com/kubernetes-sigs/service-apis/issues/84

**Comment by bowei** [comment]
(At some point,  we will have to put a link in the docstring to the concepts page to do the topic justice if we want to keep things consistent)

Binding to all routes sounds problematic to me as it is easy to fat finger.

**Comment by jpeach** [comment]
I think the simplest model consists of 3 hops:
```
client ---> gateway ---> target
```

I used "target" to avoid overloaded terminology. The phrase "routing to backends" implies the hop from gateway to target which I think is misleading. From the client perspective, the gateway is an endpoint (i.e. the client can't distinguish between the gateway and the target). HTTPRoute and friends are therefore also (logical?) endpoints that happen to be hosted in the same gateway.

> // A route allows a cluster operator to expose a service by externally-reachable URL,
// load balance traffic, terminate SSL/TLS, and offers name-based virtual hosting.

I think this is a big improvement, however I'd say that the Gateway offers name-based virtual hosting, and that HTTPRoute is a virtual host.

> // Routes can be chained together to form a hierarchy of actions to perform against
// a request.

I find this statement confusing. There's no direct support in the API for forwarding to another gateway, though if you can forward to an external DNS name, that could be a gateway (in this service-apis sense as well as in the network element sense). Recommend you drop this sentence.

**Comment by bowei** [comment]
Can you clarify what this means? "implies the hop from gateway to target" is misleading.
Remember, we should express things in terms of Kubernetes concepts (e.g. `core.Services`) as those are the most tangible for our users.
Other note is that we are currently very focused on TLS+HTTP. Yes, it's a major use case, but I don't want the API to completely be wrapped around that as  the model.

The chaining is currently sketched but not written down in the docs in the repo. We can leave that out for the time being if it becomes confusing.
