### ISSUE TITLE
[Suggestion] Have a KEP for this?

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes-sigs/service-apis#9]
TBH, I'm not sure whether the service-apis is target for replacing ingress or just offer an out-of-tree solution for kubernetes users.

If it's target for replacing ingress and `type=Loadbalancer` service, we may need to have a KEP for tracking this.

Thanks.

**Comment by bowei** [comment]
Yes there will be a KEP for which the contents will be from the work here.

**Comment by bowei** [comment]
The KEP will be a schedule and a pointer to the docs here mostly likely.

**Comment by bowei** [comment]
(No
