### ISSUE TITLE
TLS: expose an application over HTTPS

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#90]
**What would you like to be added**:

The ability to expose an application over HTTPS.

**Why is this needed**:

In the role of an application developer, I have an application (i.e. a network endpoint that clients will interact with) which has a name (i.e. a hostname). I have visited GoDaddy and purchased a TLS Certificate for that. I want to create an endpoint that will terminate HTTPS using this server  certificated bundle that I provide.

/kind user-story

**Comment by hbagdi** [comment]
/remove-lifecycle stale
xref #193

**Comment by hbagdi** [comment]
@jpeach With #281 merged in, is it safe to close this one?

**Comment by hbagdi** [comment]
Considering this resolved.
Please re-open if otherwise.
/close.
