### ISSUE TITLE
TLS: require specific TLS version or other configuration for an application

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#92]
**What would you like to be added**:

The ability for an application to specify its TLS version requirement. This extends to other TLS tunable such as cipher suites, session caching, session tickets and so forth.

**Why is this needed**:

As an application developer, my client audience is rapidly moving to TLS 1.2, but the cluster operator is also responsible for applications that will require TLS 1.1 for a long time to come. I want to be able to require TLS 1.2 on my application while allowing other applications to continue with TLS 1.1 for compatibility reasons.

The same use case applies to other TLS configuration items in general. Note that some applications will make different security/performance tradeoffs (e.g. around session tickets) so it would be inappropriate for the policy for my application to be allowed to be used for a different application.

/kind user-story

**Comment by bowei** [comment]
Can we create an overall topic for TLS configuration? (Edit the topic)

References:
* nginx http://nginx.org/en/docs/http/ngx_http_ssl_module.html
* haproxy https://www.haproxy.com/documentation/aloha/9-0/traffic-management/lb-layer7/tls/
* envoy https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto

**Comment by bowei** [comment]
This story is written from application dev standpoint, but I find that mostly TLS policy is enforced by cluster operator level (see https://kubernetes-sigs.github.io/service-apis/concepts/). 

From conversations w/ users, I have found that app dev do not care as long as someone else makes it compliant/secure.

We need to also include mention of enforcement (note such policy can enforced in other ways) if app devs have choice in the matter.

**Comment by jpeach** [comment]
I can see there could be different stories for dev and cluster operator personas. Cluster operators may define defaults and policy rules. Many dev teams will find the default acceptable, and others will need to specify them.

**Comment by jpeach** [comment]
Similar to #256, this setting can probably be added to `TLSConfig`

**Comment by hbagdi** [comment]
It is now possible to configure version specific requirement in the `Options` map. Is that sufficient for this use case, @jpeach ?

**Comment by jpeach** [comment]
Yup, let's see how it goes.

/close
