### ISSUE TITLE
TLS: accept a TLS session and forward to a TCP endpoint

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/service-apis#94]
**What would you like to be added**:

The ability for the Gateway to terminate a TLS session then tunnel the contents to an endpoint without inspecting the contents at all.

**Why is this needed**:

As an application developer, I have a non-HTTP application that is exposed as a TLS endpoint. I want to provide a server key and certificate bundle and have the Gateway present this to the client and accept TLS connections on my behalf. The encapsulated byte stream should be forwarded to my application endpoint (i.e. Kubernetes Pods, Services, etc).

/kind user-story

**Comment by bowei** [comment]
Your byte stream is TCP on the backside (to be explicit)

**Comment by hbagdi** [comment]
xref #96
/remove-lifecycle stale

**Comment by hbagdi** [comment]
This should be now possible with TCPRoute and a TLS listener.
@jpeach Do you think we should close this now?

**Comment by jpeach** [comment]
> This should be now possible with TCPRoute and a TLS listener.
> @jpeach Do you think we should close this now?

Yup, I think we are in good shape here.
