### ISSUE TITLE
All things byte stream routing

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/service-apis#96]
/kind user-story

Following are features around byte streams:
- [ ] **TCP routing**: Route all traffic on a specific LoadBalancer port or NodePort to be routed to a Service in k8s. The byte stream is passed on to the usptream service as is.
- [ ] **TLS SNI-based routing with TLS termination**: Route traffic based on the SNI in TLS client hello. The TLS session is terminated by the proxy and traffic is sent upstream. It should be possible to forward the byte stream as is or send it over a new TLS session between the proxy and upstream service. See #94
- [ ] **TLS SNI-based routing (no TLS termination)** : Route traffic based on the SNI in TLS client hello but TLS termination is not performed by the proxy. The traffic is sent to the upstream service as is. Same as #123.

The above features are for TCP only. UDP support is not part of this user-story/feature.

**Comment by bowei** [comment]
https://github.com/kubernetes-sigs/service-apis/issues/94

**Comment by hbagdi** [comment]
@jpeach @danehans I'm using this issue as an umbrella issue for all things byte stream.
I've summarized #123 and #94 here.

**Comment by jpeach** [comment]
@hbagdi One way to represent umbrella issues in GitHub is to add a list of checkboxes to the first comment. Github treats that as a task list and will show extra UI for it.

**Comment by akutz** [comment]
FWIW, this is *exactly* what #132 solved! I just closed it because I didn’t like how I handled the non TLS story.

**Comment by jpeach** [comment]
xref #66

**Comment by danehans** [comment]
xref https://github.com/kubernetes-sigs/service-apis/issues/66

**Comment by hbagdi** [comment]
All of this is now possible using TCPRoute, TLSRoute and `mode` property inside Listeners in Gateway.
/close
